### ISSUE TITLE
Onesignal notification not receiving on android 8

### ISSUE THREAD

**Issue by softsan** [OneSignal/OneSignal-Xamarin-SDK#100]
**Description:**

We are using OneSignal in our Xamarin.Forms app.  One signal is lateste from your nuget package v3.1.1 and it is not working on android 8.0. It works fine on android 6.
 

**Environment**
 
1. What version of the Xamarin SDK are you using? 
Xamarin.forms 3.0.0.482510
2. How did you add the SDK to your project (eg. nuget)
using nuget
 

**Steps to Reproduce Issue:**

1. Added version 3.1.1 of the Xamarin SDK to project
  2. Initialize the SDK with App ID
  3. Attempt to receive a push notification
4. Also change the Target Framework of Android to Api 26 (From project -> settings -> Android build)

 The notification is not received on Android 8 (Oreo) device

**Anything else:**

There are no errors or exceptions.

**Comment by Nightsd01** [comment]
@softsan can you test our latest update (3.2.0) and let me know if that resolves your issue?

**Comment by softsan** [comment]
@Nightsd01- Sorry for delay response. Yeh its works with 3.1.1 also. The problem turns out to be some "caching" on android 8.  Once it is cleared, it works fine.

Thanks for your help and support!

**Comment by Nightsd01** [comment]
#Glad to hear you got it working! If you have any other problems feel free to ask.

**Comment by EmilAlipiev** [comment]
it doesnt work for 3.0.1 but it works on 3.2.0..

**Comment by oguzhanorhaan** [comment]
I have the same issue on Android 8. I already updated to 3.2.1 but nothing change.

**Comment by vaadzz** [comment]
> @Nightsd01- Sorry for delay response. Yeh its works with 3.1.1 also. The problem turns out to be some "caching" on android 8. Once it is cleared, it works fine.
> 
> Thanks for your help and support!

Hi, could you please describe, how you fixed that issue?

**Comment by softsan** [comment]
> > @Nightsd01- Sorry for delay response. Yeh its works with 3.1.1 also. The problem turns out to be some "caching" on android 8. Once it is cleared, it works fine.
> > Thanks for your help and support!
> 
> Hi, could you please describe, how you fixed that issue?

Cleared the cache from android 8 device and then re-install the app and it works. you can read about how to clear cache/storage (if needed): https://www.lifewire.com/clear-cache-android-4157780 also you may refer this to see if any of the case is applied to you:
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown
