### ISSUE TITLE
conflict detected for Xamarin.Android.Support.Compat

### ISSUE THREAD

**Issue by GaneshSingh** [OneSignal/OneSignal-Xamarin-SDK#106]
**Description:**

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 CLUBAPP.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2.1 -> Xamarin.Android.Support.v7.Palette 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
 CLUBAPP.Android -> CLUBAPP -> Com.OneSignal 3.2.0 -> Xamarin.Android.Support.CustomTabs 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2).	

**Environment**

Visual Studio 2017
Target Framework: .NET Standard 2.0
Android : v8.1
Xamarin Forms: 3.1.0.583944

**Steps to Reproduce Issue:**

I am getting this error after adding latest version of OneSignal Sdk (3.2.0) using nugget package manger in my xamarin forms project.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by michelevirgilio** [comment]
Same here, adding CustomTabs, does not works.

Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 MYAPP.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2.1 -> Xamarin.Android.Support.v7.Palette 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
 MYAPP.Android -> MYAPP-> Com.OneSignal 3.2.0 -> Xamarin.Android.Support.CustomTabs 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2).

**Comment by jrahma** [comment]
I have the same problem but can't install Xamarin.Android.Support.CustomTabs

Getting:

Running non-parallel restore.
Reading project file /Users/jassim/Projects/myBMI/myBMI.Android/myBMI.Android.csproj.
Restoring packages for /Users/jassim/Projects/myBMI/myBMI.Android/myBMI.Android.csproj...
Restoring packages for MonoAndroid,Version=v8.1...
Resolving conflicts for MonoAndroid,Version=v8.1...
Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 myBMI.Android (>= 1.0.0) -> Xamarin.Android.Support.CustomTabs (>= 27.0.2.1) -> Xamarin.Android.Support.Compat (>= 27.0.2.1) 
 myBMI.Android (>= 1.0.0) -> Xamarin.Android.Support.Design (>= 27.0.2) -> Xamarin.Android.Support.Compat (>= 27.0.2).
Checking compatibility of packages on MonoAndroid,Version=v8.1.
Checking compatibility for myBMI.Android 1.0.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.CustomTabs 27.0.2.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Design 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v7.AppCompat 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v4 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v7.CardView 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v7.MediaRouter 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.SfTabView 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.SfBusyIndicator 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.SfNumericTextBox 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Com.OneSignal 3.2.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Microsoft.AppCenter.Analytics 1.8.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Microsoft.AppCenter.Crashes 1.8.0 with MonoAndroid,Version=v8.1.
Checking compatibility for AppCenter.Analytics.Metrics 1.0.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Newtonsoft.Json 11.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Forms 3.1.0.697729 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.Buttons 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Essentials 0.9.1-preview with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Auth 1.6.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Microsoft.AppCenter 1.8.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.SfPopupLayout 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.SfListView 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for myBMI 1.0.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Compat 27.0.2.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v7.RecyclerView 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Transition 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Core.UI 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Core.Utils 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Fragment 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Media.Compat 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Vector.Drawable 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Animated.Vector.Drawable 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.v7.Palette 27.0.2 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Licensing 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.GooglePlayServices.Gcm 42.1021.1 with MonoAndroid,Version=v8.1.
Checking compatibility for NETStandard.Library 1.6.1 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Numerics.Vectors 4.5.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.DataSource 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.GridCommon 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Syncfusion.Xamarin.Core 16.2.0.46 with MonoAndroid,Version=v8.1.
Checking compatibility for Skybrud.Essentials 1.1.5 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Support.Annotations 27.0.2.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.Runtime 1.0.3.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.GooglePlayServices.Base 42.1021.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.GooglePlayServices.Basement 42.1021.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.GooglePlayServices.Iid 42.1021.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Microsoft.Win32.Primitives 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.AppContext 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Collections 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Collections.Concurrent 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Console 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Diagnostics.Debug 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Diagnostics.Tools 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Diagnostics.Tracing 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Globalization 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Globalization.Calendars 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.IO 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.IO.Compression 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.IO.Compression.ZipFile 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.IO.FileSystem 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.IO.FileSystem.Primitives 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Linq 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Linq.Expressions 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Net.Http 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Net.Primitives 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Net.Sockets 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.ObjectModel 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Reflection 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Reflection.Extensions 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Reflection.Primitives 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Resources.ResourceManager 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime.Extensions 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime.Handles 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime.InteropServices 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime.InteropServices.RuntimeInformation 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Runtime.Numerics 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Security.Cryptography.Algorithms 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Security.Cryptography.Encoding 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Security.Cryptography.Primitives 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Security.Cryptography.X509Certificates 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Text.Encoding 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Text.Encoding.Extensions 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Text.RegularExpressions 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Threading 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Threading.Tasks 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Threading.Timer 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Xml.ReaderWriter 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Xml.XDocument 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for System.Xml.XPath.XDocument 4.3.0 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.Common 1.0.3.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Android.Arch.Core.Common 1.0.0.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.GooglePlayServices.Tasks 42.1021.1 with MonoAndroid,Version=v8.1.
Checking compatibility for Xamarin.Build.Download 0.4.2 with MonoAndroid,Version=v8.1.
All packages and projects are compatible with MonoAndroid,Version=v8.1.
Package restore failed. Rolling back package changes for 'myBMI.Android'.

**Comment by AngeloLazzari** [comment]
i solved by uninstall all the dependencies and starting adding one after the other, reading what the message says: for example, if it says that you have to directly to link Xamarin.Android.Support.Compat,  link it, and if during the linking it says you have to previous add another dependendy from another library, well, you have to add it, you.ll se that step by step you ll get the solution.

**Comment by ugnivs** [comment]
@jkasten2 When will be the update to support v28?

**Comment by niketan07** [comment]
[this](https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/) solved my similar issues.

**Comment by bbl-Laobu** [comment]
Hello, any update on this? Support for Xamarin.Android.Support.Compat (>= 28.0.0.1) would be great.

**Comment by rgomezp** [comment]
We have released a new version and this should no longer be an issue!

Cheers

**Comment by MarcoSal** [comment]
i have similari issue with Xamarin.Android.Support to 28.0.0.3
https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/239

I couldn't find a solution ...
