### ISSUE TITLE
Privacy GPDR for users

### ISSUE THREAD

**Issue by AngeloLazzari** [OneSignal/OneSignal-Xamarin-SDK#113]
I read [here](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.9.0) in the Android SDK 3.9 you added the PrivacyConsent, is there the same login on XMARIN version or we have to follow the instruction from both android and IOS SDKs? 

thank you very much

**Comment by jkasten2** [comment]
@AngeloLazzari There is specific Xamarin documentation below for `SetRequiresUserPrivacyConsent` and `UserDidProvidePrivacyConsent` methods.
https://documentation.onesignal.com/docs/xamarin-sdk#section--setrequiresuserprivacyconsent-

**Comment by AngeloLazzari** [comment]
Thank you very much!!
