### ISSUE TITLE
targeting multiple user devices

### ISSUE THREAD

**Issue by AngeloLazzari** [OneSignal/OneSignal-Xamarin-SDK#114]
Hi we are using your great service but now, after we read you complete documentation we wanted to cover this situation: a user can login the app from different devices.

Initially we thought it was a good idea to store the differents OneSignal Player IDs in our back end, but, now we saw that another solution would be to use **tags** for the user that permit, using the user_id to express the ONE to MANY relation about USER and his devices.

But, the question we didn't answer is: how we can send push notifications targeting the user_id that i passed as tag?

thank you very much
Angelo

**Comment by jkasten2** [comment]
@AngeloLazzari You can use `filters` when sending your notification through the OneSignal REST API noted below.
https://documentation.onesignal.com/reference#section-send-to-users-based-on-filters

For future questions on the OneSignal REST API and dashboard we recommend contacting OneSignal support as this repo is specific to the Xamarin SDK. Thanks!

**Comment by AngeloLazzari** [comment]
thank you very much @jkasten2 !
