### ISSUE TITLE
GPRD: coding it correctly

### ISSUE THREAD

**Issue by AngeloLazzari** [OneSignal/OneSignal-Xamarin-SDK#115]
Hi, as i read in this documentation [here](https://documentation.onesignal.com/docs/xamarin-sdk#section--serrequiresuserprivacyconsent-) i coded as follow:

IN MY App.xaml.cs i put:
            
// IF THE USER DOESn'T ALREADY GIVE THE PERMISSIONS
if (OneSignal.Current.RequiresUserPrivacyConsent() == true)
      //DELAY THE INITIALIZATION TILL THE USER CANNOT GIVE HIS PERMISSION
      OneSignal.Current.SetRequiresUserPrivacyConsent(true);

OneSignal.Current.StartInit("XXXXXXXXXXXXXX").EndInit();

do i need to code it into the Android project too or it is OK like that? 

Managing the Permission on my own, do i have to put the to ask the user the permission?
 <meta-data android:name="com.onesignal.PrivacyConsent" android:value="ENABLE" />

Thank you very much
Angelo

**Comment by jkasten2** [comment]
@AngeloLazzari If `App.xaml.cs` is used by both iOS and Android then you don't need add anything specifically for Android.

You will need to provide a privacy policy for the user to read and then only call `OneSignal.Current.UserDidProvidePrivacyConsent(true);` after they have accepted it. You only need to call `UserDidProvidePrivacyConsent` once, the OneSignal SDK will remember their answer when the app is reopened.

**Comment by AngeloLazzari** [comment]
ok thank you!
Angelo
