### ISSUE TITLE
SetSubscription is not functional 

### ISSUE THREAD

**Issue by abdullam09** [OneSignal/OneSignal-Xamarin-SDK#116]
**Description:**

Hi,

i am using onesignal in xamarin.forms and it's working fine, i am getting notifications from the portal.
but when i try to SetSubscription(false), the portal doesn't show it's not subscrpied and i am still getting notifications.

i do the SetSubscription(false) after i get registered to onesignal service. here is part of the code

in App.xaml
OneSignal.Current.StartInit("")
.HandleNotificationOpened(HandleNotificationOpened)
.EndInit();
OneSignal.Current.IdsAvailable(IdsAvailable);

private void IdsAvailable(string userID, string pushToken)
    {

                OneSignal.Current.SetSubscription(false);

    }
also in the website it does mention how to use the SetSubscription, by using "OneSignal.SetSubscription(false);"
but after i install the sdk there is no SetSubscription in onesignal, the function only in OneSignal.Current

Thanks for the help

**Environment**
xamarin forms sdk 3.2.0.839982
Onesignal 3.2.1

**Comment by PauchardThomas** [comment]
Same problem any idea ??
SetSubscription(false) seems to not working sometimes.
XF : 3.3.0
Onesignal 3.2.2

**Comment by rgomezp** [comment]
Hello,
Thank you for your patience. We have since released an update to the plugin. Could you please test it? We would be happy to help anyway we can if you are still facing the issue

**Comment by rgomezp** [comment]
Closing due to no response
