### ISSUE TITLE
Is that possible to handle notification like "HandleNotificationReceived" method when app is closed or backgrounding?

### ISSUE THREAD

**Issue by kelvin195eclipse** [OneSignal/OneSignal-Xamarin-SDK#118]
Hi,

First of all, big thanks to this SDK!

Anyway I would like to know whether there is any method to handle notifications like "HandleNotificationReceived" method, when the app is closed, not opened or in the background?

Thanks!

**Comment by ArgusMagnus** [comment]
Theoretically you should be able to achieve this with a NotificationServiceExtension (#33), I cannot get this to work however.

**Comment by nhdanh** [comment]
any solution for this ?

**Comment by nhdanh** [comment]
I cannot fire a HandleNotificationReceived in background. It only fire when in app focus

**Comment by rgomezp** [comment]
Hello,
Are y'all referring to iOS or Android in this case?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by felipechavez** [comment]
hi @rgomezp , i have this issue in some iPhone devices. Android is working perfectly.
In iPhone 7 there is no problem with the iOS 13 version, but in iPhone 6 and iPhone XR looks like the app is completely closed. Only fired up on the method HandleNotificationReceived when is in background and in focus, but not when the app is closed. It's weird.
