### ISSUE TITLE
Additional payload sent with the notification is being incorrectly displayed

### ISSUE THREAD

**Issue by mkieres** [OneSignal/OneSignal-Xamarin-SDK#12]
Hello

We’re using the latest OneSignal Xamarin SDK in a project that targets iOS. I ran into an issue where the additional payload sent with the notification is being incorrectly displayed to the user as an alert (see attached image). We’re using an Azure push notification hub to send out the remote notifications, with a template that’s structured similar to the following:

{"aps":{"alert":"$(s)"}, "m":"$(m)"};

The $(s) is a token that is replaced with a user friendly message to appear in the alert. This works when the application is in the background and the user sees the correct notification appear.
The $(m) is a json payload that should be parsed by the application. 

Prior to adding the OneSignal SDK the application behaved correctly with the alert appearing when the application is in the background (or closed). If the application is in the foreground the user doesn’t see any alert. 
After adding the OneSignal SDK, the behavior when the application is in the background (or closed) remained the same. Unfortunately when the application is in the foreground, a notification, with the json payload as its contents, is displayed in the notifications area.

We think that the OneSignal SDK is attempting to handle our notification by displaying the payload to the user via a local notification. Is there a way that we can intercept, or disable, this behaviour?

![pushnotificationwrongformatting_onesignal](https://cloud.githubusercontent.com/assets/8372764/17999163/6d43ca3e-6bbb-11e6-93d3-df5a2a9fa741.PNG)

**Comment by jkasten2** [comment]
@mkieres The OneSignal SDK uses the `"m"` field as a key for display a notification with action buttons. You will need to use a different key so this doesn't conflict with OneSignal.

**Comment by jkasten2** [comment]
@mkieres Feel free to reopen this issue if this doesn't work for you.

Thanks.
