### ISSUE TITLE
Update Com.OneSignal package from 3.0.1 to 3.2.0 PROGUARD warnings

### ISSUE THREAD

**Issue by aboulinguez** [OneSignal/OneSignal-Xamarin-SDK#120]
**Description:**
Hi the OneSignal team,

I'm trying to update my Com.OneSignal package from 3.0.1 to 3.2.0.
(in order to fix push notifications on Android >= 8.0)

I'm facing these errors:

```
3>PROGUARD : warning : com.onesignal.ADMMessageHandler: can't find referenced method 'android.content.Context getApplicationContext()' in program class com.onesignal.ADMMessageHandler
3>PROGUARD : warning : com.onesignal.OSUtils: can't find referenced class com.google.firebase.messaging.FirebaseMessaging
3>PROGUARD : warning : com.onesignal.PushRegistratorFCM: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
3>PROGUARD : warning : com.onesignal.PushRegistratorFCM: can't find referenced class com.google.firebase.messaging.FirebaseMessaging
3>PROGUARD : warning : com.onesignal.PushRegistratorFCM: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
3>PROGUARD : warning : com.onesignal.PushRegistratorFCM: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
3>PROGUARD : warning : com.onesignal.PushRegistratorFCM: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
3>PROGUARD : warning : there were 6 unresolved references to classes or interfaces.
3>PROGUARD : warning : there were 1 unresolved references to program class members.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2464,3): error MSB6006: "java.exe" exited with code 1.
```

- Android Target/Compile version: 8.1
- Same problem with the 3.2.1 version of the package.
- Only in Release mode.

I'm currently not able to build a new package for my Android app..

Any idea?

Thanks in advance for your help.

**Comment by aboulinguez** [comment]
Same problem with 3.1.1

**Comment by EmilAlipiev** [comment]
this looks proguard issue. do you use proguard?

**Comment by aboulinguez** [comment]
Yes I do, proguard in enabled in release mode of my Xamarin Android project.

**Comment by EmilAlipiev** [comment]
Do you still have this problem? i also use proguard and i dont have the problem. here is my proguard set up. A lot of to keep but i couldnt find a better solution. try and let me know please

```


## Onesignal

-dontwarn com.onesignal.**
-keep class com.onesignal.** { *; } 
-keep class com.google.android.gms.common.api.GoogleApiClient {
    void connect();
    void disconnect();
}
-keep public interface android.app.OnActivityPausedListener {*;}
-keep class com.onesignal.ActivityLifecycleListenerCompat** {*;}
-keep class com.onesignal.OSSubscriptionState {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSSubscriptionState {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSPermissionChangedInternalObserver {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSSubscriptionChangedInternalObserver {
    void changed(com.onesignal.OSSubscriptionState);
}

-keep class ** implements com.onesignal.OSPermissionObserver {
    void onOSPermissionChanged(com.onesignal.OSPermissionStateChanges);
}

-keep class ** implements com.onesignal.OSSubscriptionObserver {
    void onOSSubscriptionChanged(com.onesignal.OSSubscriptionStateChanges);
}

-keep class com.onesignal.shortcutbadger.impl.AdwHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.ApexHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.AsusHomeLauncher { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.DefaultBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.EverythingMeHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.HuaweiHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.LGHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.NewHtcHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.NovaHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.OPPOHomeBader { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.SamsungHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.SonyHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.VivoHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.XiaomiHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.ZukHomeBadger { <init>(...); }
 
```

**Comment by aboulinguez** [comment]
Hi,

I’ve switch to other projects for the moment but as soon as I will go back to our project using OneSignal, I will check this.

Thanks for your message.

De : Emil Alipiev <notifications@github.com>
Envoyé : mercredi 12 décembre 2018 15:46
À : OneSignal/OneSignal-Xamarin-SDK <OneSignal-Xamarin-SDK@noreply.github.com>
Cc : aboulinguez <antoine-boulinguez@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [OneSignal/OneSignal-Xamarin-SDK] Update Com.OneSignal package from 3.0.1 to 3.2.0 PROGUARD warnings (#120)


Do you still have this problem? i also use proguard and i dont have the problem. here is my proguard set up. A lot of to keep but i couldnt find a better solution. try and let me know please





## Onesignal



-dontwarn com.onesignal.**

-keep class com.onesignal.** { *; }

-keep class com.google.android.gms.common.api.GoogleApiClient {

    void connect();

    void disconnect();

}

-keep public interface android.app.OnActivityPausedListener {*;}

-keep class com.onesignal.ActivityLifecycleListenerCompat** {*;}

-keep class com.onesignal.OSSubscriptionState {

    void changed(com.onesignal.OSPermissionState);

}



-keep class com.onesignal.OSSubscriptionState {

    void changed(com.onesignal.OSPermissionState);

}



-keep class com.onesignal.OSPermissionChangedInternalObserver {

    void changed(com.onesignal.OSPermissionState);

}



-keep class com.onesignal.OSSubscriptionChangedInternalObserver {

    void changed(com.onesignal.OSSubscriptionState);

}



-keep class ** implements com.onesignal.OSPermissionObserver {

    void onOSPermissionChanged(com.onesignal.OSPermissionStateChanges);

}



-keep class ** implements com.onesignal.OSSubscriptionObserver {

    void onOSSubscriptionChanged(com.onesignal.OSSubscriptionStateChanges);

}



-keep class com.onesignal.shortcutbadger.impl.AdwHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.ApexHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.AsusHomeLauncher { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.DefaultBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.EverythingMeHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.HuaweiHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.LGHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.NewHtcHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.NovaHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.OPPOHomeBader { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.SamsungHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.SonyHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.VivoHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.XiaomiHomeBadger { <init>(...); }

-keep class com.onesignal.shortcutbadger.impl.ZukHomeBadger { <init>(...); }

**Comment by rgomezp** [comment]
Closing for now. Let me know if you would like me to reopoen

**Comment by ndastur** [comment]
Would be good to put this proguard config in the docs
