### ISSUE TITLE
Error  Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by javitoHertfy** [OneSignal/OneSignal-Xamarin-SDK#122]
**Description:**

I have followed all the instructions listed in the documentation and once I launch the application I get the following error:

Unhandled Exception:

Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.fxstreet.mobile. Make sure to call FirebaseApp.initializeApp(Context) first. occurred

**Environment**

Nuget packages
Xamarin Forms v 3.4
Xamarin Firebase Messaging and the rest of GooglePlayServices 42.1021 

**Steps to Reproduce Issue:**

Followed steps described in documentation 
1. Added all the nugets with the right version
2. Add the code in the xaml.cs and in the MainActivity
3. Changed Manifest 

**Anything else:**

The application starts but gets unresponsive quickly and throws the error

**Comment by jkasten2** [comment]
@javitoHertfy Thanks for the details, could you and provide the full stack trace?

**Comment by rgomezp** [comment]
closing due to no response
