### ISSUE TITLE
NotificationExtenderService in Xamarin SDK

### ISSUE THREAD

**Issue by Osmosis311** [OneSignal/OneSignal-Xamarin-SDK#123]
Is there any chance you will consider adding the NotificationExtenderService functionality to the Xamarin SDK?

Thank you.

**Comment by ArgusMagnus** [comment]
It already is: https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

I use this class and it works fine:

	/// <summary>
	/// Necessary to receive background notifications:
	/// https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding
	/// </summary>
	[Service(Permission = "android.permission.BIND_JOB_SERVICE", Exported = false)]
	[IntentFilter(actions: new[] { "com.onesignal.NotificationExtender" })]
	public sealed class OneSignalNotificationExtenderService : Com.OneSignal.Android.NotificationExtenderService
	{
		static readonly OverrideSettings _displaySettings = new OverrideSettings() { Extender = new Extender() };

		protected override bool OnNotificationProcessing(OSNotificationReceivedResult p0)
		{
			var notification = Com.OneSignal.NotificationOpenedHandler.OSNotificationToNative(new OSNotification() { Payload = p0.Payload });
			var task = App.OnNotificationReceivedAsync(notification);
			DisplayNotification(_displaySettings);
			task.Wait();
			return true;
		}

		protected override void OnHandleIntent(Intent intent) { }

		sealed class Extender : Java.Lang.Object, NotificationCompat.IExtender
		{
			public NotificationCompat.Builder Extend(NotificationCompat.Builder builder)
			{
				var soundUri = App.Data.RingtoneUri;
				if (string.IsNullOrWhiteSpace(soundUri))
					return builder;
				return builder
					.SetDefaults(~(int)NotificationDefaults.Sound)
					.SetSound(Android.Net.Uri.Parse(soundUri));
			}
		}
	}
