### ISSUE TITLE
Not synchronizing on a android service

### ISSUE THREAD

**Issue by nicruo** [OneSignal/OneSignal-Xamarin-SDK#13]
On a android service, calling the onesignal.sendtag method does not update the tags on the OneSignal Dashboard. Only when I open the application (a activity) it works doing the synchronization of all the tags sent before.

**Comment by jkasten2** [comment]
@nicruo This maybe an bug in the [OneSignal Android 2.6.0 SDK](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/2.6.0) used by the 0.9.6 version of this SDK. We will be updating this SDK to use the latest OneSignal Android Native 3.2.0 in the coming weeks which I believe will fix this issue.

**Comment by jkasten2** [comment]
@nicruo Can you try our 2.0 Xamarin SDK to see if this is now fixed for you?

**Comment by jkasten2** [comment]
@nicruo We haven't had any other reports of this. Please feel free to reopen this issue if you are able to reproduce this our 2.1.0 SDK.
