### ISSUE TITLE
Badge count don't reset after open App (iOS)

### ISSUE THREAD

**Issue by paolo2796** [OneSignal/OneSignal-Xamarin-SDK#132]
Description:

Push notifications and incrementing of the badge count all work perfectly. Unfortunately, while the badge is "cleared", when a new notification comes through, it resumes with the previous badge count rather than starting from 0.

Environment
- OneSignal-Xamarin-SDK 3.2.2 (last stable version);
- Visual Studio for Mac 2017 (last stable versione);
- Xamarin Forms 3.4.0;
- OneSignalNotificationServiceExtension (added group app name);
- Setup App Groups in App Developer Account;

Steps to Reproduce Issue:
Attempt to receive a push notification
Badge count bumps to 1.
Open app, clearing the iOS badge
Attempt to receive a push notification
Badge count bumps to 2, but should be 1 again after having been "cleared"

**Comment by paolo2796** [comment]
This is configuration OneSignalNotificationServiceExtension (info.plist and Entitlements.plist) solution:
![infoplist_onesignalextension](https://user-images.githubusercontent.com/32263147/51969679-59ed2c80-2475-11e9-937b-e5c6f96157e1.png)
![entitlements_onesignalextension](https://user-images.githubusercontent.com/32263147/51969680-59ed2c80-2475-11e9-8045-3b7cfaef5239.png)

and MyProject (info.plist and Entitlements.plist) solution:
![infoplist_myproject](https://user-images.githubusercontent.com/32263147/51969870-c536fe80-2475-11e9-976f-e3d5bfb24931.png)
![schermata 2019-01-30 alle 10 03 01 copia](https://user-images.githubusercontent.com/32263147/51970139-645bf600-2476-11e9-8563-f47ff8cee159.png)


while this is my app developer account configuration (App group name)
![schermata 2019-01-30 alle 10 05 09 copia](https://user-images.githubusercontent.com/32263147/51970226-a38a4700-2476-11e9-8e1c-456ad7dddf72.png)
:

**Comment by Ankush-Redapple** [comment]
Please follow https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup in detail.

> The name of your app group should be group.{your_bundle_id}.onesignal. So for example, if your application's bundle identifier is com.test.app, your app group name should be group.com.test.app.onesignal.
> 
> [Assign the group to both target](https://files.readme.io/9e17c8c-OneSignal_Xcode_app_groups_capabilites.png).
> 
> 1. Open your Info.plist file and add a new OneSignal_app_groups_key as a String type.
> 2. Enter the group name you checked in the last step as it's value.
> 3. Make sure to do the same for the Info.plist under the OneSignalNotificationServiceExtension folder.
