### ISSUE TITLE
Targeting android 9.0 full linking exception upon incoming notification

### ISSUE THREAD

**Issue by taublast** [OneSignal/OneSignal-Xamarin-SDK#136]
**Description:**
When i compile targeting up to Android 8.1 everything is okay, but targeting Android 9.0 gives the following exception *upon receiving notification*:

> Java.Lang.RuntimeException: Unable to instantiate receiver com.onesignal.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.GcmBroadcastReceiver"

Full linking: user assemblies and sdk.
Com.OneSignal 3.2.2
Xamarin Forms 3.5.16..
Tested on simulator AND real device with Android 6.1 installed.

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay. Could you try following the instructions in my response on post #135 ?

Cheers

**Comment by rgomezp** [comment]
Closing due to no response
