### ISSUE TITLE
Can we please have a way to handle push notifications silently for both iOS and Android?

### ISSUE THREAD

**Issue by pooran** [OneSignal/OneSignal-Xamarin-SDK#137]
There are some maintenance push messages that we are sending. But we are not able to handle them silently. this to avoid multiple notifications and android and ios restrictions for apps going to idle mode or battery optimization modes etc.

**Comment by rgomezp** [comment]
Please see our docs for more information on background notifications (both ios and android): https://documentation.onesignal.com/docs/silent-notifications
