### ISSUE TITLE
Please consider removing dependancy on Xamarin.GooglePlayServices.Gcm

### ISSUE THREAD

**Issue by ndastur** [OneSignal/OneSignal-Xamarin-SDK#142]
**Description:**
GCM is now depreciated in favour of FCM. The Xamarin.GooglePlayServices.Gcm package causes NuGET conflicts and it would appear is an unnecessary dependancy.

(your description here)

**Environment**
Building a shared Xamarin Forms project
Install via NuGET

**Steps to Reproduce Issue:**
Create a blank XF project
Add package such as Kinvey for mobile backend.
Add OneSignal 3.1.0 package

NuGET error 
```
Resolving conflicts for MonoAndroid,Version=v9.0...
NU1107: Version conflict detected for Xamarin.GooglePlayServices.Basement. Install/reference Xamarin.GooglePlayServices.Basement 60.1142.1 directly to project myapp.Android to resolve this issue. 
 myapp.Android -> Kinvey 4.0.1 -> Xamarin.GooglePlayServices.Basement (>= 60.1142.1) 
 HospifyProbe.Android -> Com.OneSignal 3.3.0 -> Xamarin.GooglePlayServices.Gcm 42.1021.1 -> Xamarin.GooglePlayServices.Basement (= 42.1021.1).
```

**Comment by rgomezp** [comment]
Hello,
Thanks for bringing this up. We will fix this in the next update.

Best

**Comment by mengvisal** [comment]
@rgomezp can you consider fixing this problem soon? We are about to release new app but now stuck with this notification issue on android.

**Comment by rgomezp** [comment]
@mengvisal ,
I'm sorry this is blocking your release. I will go ahead and elevate to medium priority

**Comment by xDelivered-Patrick** [comment]
Hey guys - any update on this?
 
This is also affecting one my releases (actually we ended up taking out OneSignal, but i'd love to add it back in again).  Even a beta nuget package would be greatly appreciated!

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay. We are working hard to get this done as soon as possible! Thank you for your patience.

**Comment by omrivm** [comment]
This is also a blocker for us

**Comment by rgomezp** [comment]
@omrivm ,
Late next week

If you're a paying customer, please contact us through our official support channel at OneSignal.com

**Comment by omrivm** [comment]
Any news regarding this issue?

**Comment by rgomezp** [comment]
@omrivm ,
Apologies for the delay. We are trying to release all of our SDKs as soon as possible. We really appreciate everyone's patience here. We're working extra hard to push all of the updates.

**Comment by jkasten2** [comment]
The dependency for the OneSignal SDK has been changed to Firebase Messaging (FCM) in the nuspec in 3.4.0.
https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.4.0

If GCM is still in your project after the upgrade you can remove it from your packages in your project.
