### ISSUE TITLE
  Lcom/google/android/gms/iid/zzc

### ISSUE THREAD

**Issue by lumisoftusa** [OneSignal/OneSignal-Xamarin-SDK#145]
i m using latest version of Xamarin forms when i add onesignal from nuget i git this error.
java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/iid/zzc

**Comment by rgomezp** [comment]
I would be happy to help you sort this issue out. However, we do have an issue template to make things easier for us to help you. Please use the template when opening a new issue @lumisoftusa
