### ISSUE TITLE
UnsubscribeWhenNotificationsAreDisabled is not available

### ISSUE THREAD

**Issue by jeanplevesque** [OneSignal/OneSignal-Xamarin-SDK#149]
**Description:**
The boolean option "UnsubscribeWhenNotificationsAreDisabled" is available in OneSignal-Android-SDK, but is not available in the OneSignal-Xamarin-SDK.

**Environment**
Latest OneSignal-Xamarin-SDK code base.
(Commit 09c98a2 as of posting this)

**Steps to Reproduce Issue:**
1. Search for "UnsubscribeWhenNotificationsAreDisabled" in the OneSignal-Xamarin-SDK code base.
2. No results are found.

**Expected Result**
The option should be publicly exposed through the `XamarinBuilder` class.

**Comment by rgomezp** [comment]
Thanks for your patience while we consider your request

**Comment by mikechoch** [comment]
Thank you for catching this, fixed in newest release 3.4.0.

**Comment by jeanplevesque** [comment]
I just updated to version 3.4.1 and confirm this is now present and that it works correctly.
Many thanks!
