### ISSUE TITLE
Build error on Android if OkHTTP package is used

### ISSUE THREAD

**Issue by rudyryk** [OneSignal/OneSignal-Xamarin-SDK#15]
Seems  like OneSignal SDK provides a copy of OkHTTP within an assembly which conflicts with manually  added NuGet OkHTTP package https://www.nuget.org/packages/Square.OkHttp

The build error text:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:
Error: java.lang.IllegalArgumentException: already added :  Lokio/AsyncTimeout$1; 
```

**Comment by jkasten2** [comment]
@rudyryk We don't use OkHTTP or any other networking / HTTP libraries in this SDK or our included [native OneSignal Android SDK](https://github.com/OneSignal/OneSignal-Android-SDK). The conflict must be with anther SDK or library in your project.

**Comment by rudyryk** [comment]
@jkasten2 I see, then it's unclear what is the real reason, but anyway, I wasn't able to compile my project with both OneSignal SDK and OkHttp.

1. When only OneSignal SDK is present, all is OK
2. When I add OkHttp, I get the error above
3. When I remove OneSignal SDK, all is OK again

Finally, I need to opted-out using OkHttp for now. As a workaround, I used [AndroidAsync lib](https://github.com/mattleibow/AndroidAsync-binding).
