### ISSUE TITLE
Support for UWP and macOS

### ISSUE THREAD

**Issue by GKG4** [OneSignal/OneSignal-Xamarin-SDK#150]
Since there is no update on UWP SDK and macOS SDK, any update or roadmap on this please?

We all are looking for this feature badly, therefore, kindly atleast provide us an update if we can have it in future or not?

**Comment by rgomezp** [comment]
Howdy,
This isn't the right repository for your issue. In either case, we're not planning on building this any time in the near future. You can take a look at these resources in the meantime:

- https://documentation.onesignal.com/docs/macos-app-sdk-setup
- https://github.com/OneSignal/OneSignal-macOS-SDK
