### ISSUE TITLE
GooglePlayGames Conflict 71.1600.0

### ISSUE THREAD

**Issue by NVentimiglia** [OneSignal/OneSignal-Xamarin-SDK#157]
**Description:**
Nuget conflict when upgrading packages.

When upgrading the following packages, I get a conflict error. I need to uninstall OneSignal to do so. Would like to include OneSignal and these packages but requires OneSignal to upgrade support for GooglePlayGames.

**Environment**
Android.

**Steps to Reproduce Issue:**

Install these packages
```xml
    <PackageReference Include="Xamarin.Android.Support.Core.Utils">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Facebook.AccountKit.Android">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Auth">
      <Version>71.1600.0</Version>
    </PackageReference>
```

**Comment by jkasten2** [comment]
@NVentimiglia Please provide the following details.

1. `OneSignal-Xamarin-SDK` version.
2. The exact package you are upgrading.
   - Include both the from and to versions.
3. The full error from the Visual Studio log when you upgrade.

**Comment by NVentimiglia** [comment]
This resolved with the latest version
