### ISSUE TITLE
How to set notification icon?

### ISSUE THREAD

**Issue by omrivm** [OneSignal/OneSignal-Xamarin-SDK#159]
Hi,
I'm using v3.3.0 and I'm trying to set the notification icon.
In the documentation there are some options:
https://documentation.onesignal.com/docs/customize-notification-icons
But none are related to Xamarin.
Would love for some help.

**Comment by rgomezp** [comment]
Howdy,
The documentation you referenced include Xamarin info. So I'm not sure what exactly you're looking for. I would encourage you to reach out through our support channel at onesignal.com if you would like further assistance.
