### ISSUE TITLE
Location permission exists but there was an error initializing

### ISSUE THREAD

**Issue by NVentimiglia** [OneSignal/OneSignal-Xamarin-SDK#162]
**Description:**
I see this error in the output when resuming the app :

08-13 06:42:18.159 W/OneSignal(11341): Location permission exists but there was an error initializing: 
08-13 06:42:18.159 W/OneSignal(11341): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationServices;

**Environment**
Android
Xamarin 4.1.06
Com.OneSignal 3.4.1
Xamarin.GooglePlayServices.Base (>= 71.1610.0)

**Steps to Reproduce Issue:**
Run the application, background it, resume it

** Stack Trace**
08-13 06:42:18.159 W/OneSignal(11341): Location permission exists but there was an error initializing: 
08-13 06:42:18.159 W/OneSignal(11341): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationServices;
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.LocationGMS.startGetLocation(LocationGMS.java:191)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.LocationGMS.getLocation(LocationGMS.java:172)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.OneSignal.startLocationUpdate(OneSignal.java:870)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.OneSignal.startRegistrationOrOnSession(OneSignal.java:847)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.OneSignal.doSessionInit(OneSignal.java:762)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1214)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:207)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:121)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:78)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.Application.dispatchActivityResumed(Application.java:219)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.Activity.onResume(Activity.java:1312)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
08-13 06:42:18.159 W/OneSignal(11341): 	at md5d6c4d51e5ff7f2ad4be0d592099c5041.MainActivity.n_onResume(Native Method)
08-13 06:42:18.159 W/OneSignal(11341): 	at md5d6c4d51e5ff7f2ad4be0d592099c5041.MainActivity.onResume(MainActivity.java:40)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.Activity.performResume(Activity.java:7084)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3690)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3755)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.os.Looper.loop(Looper.java:164)
08-13 06:42:18.159 W/OneSignal(11341): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
08-13 06:42:18.159 W/OneSignal(11341): 	at java.lang.reflect.Method.invoke(Native Method)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-13 06:42:18.159 W/OneSignal(11341): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
08-13 06:42:18.159 W/OneSignal(11341): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationServices" on path: DexPathList[[zip file "/data/app/com.agrisync.dev3-3oS3UWbWGoIFvDVhk0P-Cg==/base.apk"],nativeLibraryDirectories=[/data/app/com.agrisync.dev3-3oS3UWbWGoIFvDVhk0P-Cg==/lib/arm64, /data/app/com.agrisync.dev3-3oS3UWbWGoIFvDVhk0P-Cg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
08-13 06:42:18.159 W/OneSignal(11341): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-13 06:42:18.159 W/OneSignal(11341): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-13 06:42:18.159 W/OneSignal(11341): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-13 06:42:18.159 W/OneSignal(11341): 	... 25 more
08-13 06:42:18.170 I/OneSignal(11341): Device registered, push token = eAtAMTA8qDY:APA91bEH5X8vsAI5Uu6Gr3ItPbvAhKXoqPwmMoo4r3LbGpbEMj9uzqmhTDK9g_a2QpcVgz1ZbwlK-GH0X6f3eoCwU5ZNuofXwVjiTxjOmxMnQl6hyMEStujCDxvDC7VeX-sqt7VW5Dla
08-13 06:42:18.186 I/OneSignal(11341): scheduleSyncServiceAsJob:result: 1

**Comment by rgomezp** [comment]
Try removing the location permission from your manifest

**Comment by rgomezp** [comment]
Closing due to no response
