### ISSUE TITLE
OSNotification.isAppInFocus is always false on Android

### ISSUE THREAD

**Issue by RodgerLeblanc** [OneSignal/OneSignal-Xamarin-SDK#163]
**Description:**
OSNotification.isAppInFocus is always false on Android, even when receiving a notification while the app is in focus.

**Environment**
Xamarin.Forms 3.6.0.344457
Com.OneSignal 3.4.1 (nuget)

**Steps to Reproduce Issue:**

1. Add version 3.6.0.344457 of the Xamarin SDK to your project
1. Add version 3.4.1 of the Com.OneSignal nuget to your project
1. Initialize the SDK with your App ID and register a delegate for received notifications
1. Inspect a received notification while the app is in focus

**Comment by rgomezp** [comment]
Thanks for your PR. We will review it soon. Cheers

**Comment by stesvis** [comment]
Having the same issue, always `false`. Following
