### ISSUE TITLE
Unable to use OneSignal on UWP (Xamarin Forms)

### ISSUE THREAD

**Issue by jrahma** [OneSignal/OneSignal-Xamarin-SDK#165]
Hi,

I am getting:

System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

You should support all Xamarin Forms platforms guys especially when you are a Microsoft Partner now

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by rgomezp** [comment]
Thanks for your request. We will continue consideration while tracking internally. Cheers

**Comment by fzany** [comment]
@rgomezp ,
I am getting this issue. Even if you're not going to implement for UWP, you can as well initialize blank methods so the UWP in Xamarin project do not crash. 

I am getting the same error. 

@jrahma, how did you fix this?
