### ISSUE TITLE
Default FirebaseApp failed to initialize because no default options were found.

### ISSUE THREAD

**Issue by srdmnc** [OneSignal/OneSignal-Xamarin-SDK#168]
**Description:**
I can't receive notification even after setting up OneSignal into my Xamarin Forms Application.

**Environment**

1. v3.5.0
2. Nuget

**Steps to Reproduce Issue:**

  1. Add version 3.5.0 of the Xamarin SDK to your project
  2. Initialize the SDK with your App ID
  3. Attempt to receive a push notification

**Stacktrace:**
`[FirebaseApp] Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
[FirebaseInitProvider] FirebaseApp initialization unsuccessful`

`[OneSignal] Unknown error getting FCM Token
[OneSignal] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getToken(java.lang.String, java.lang.String)' on a null object reference
[OneSignal] 	at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:83)
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
[OneSignal] 	at java.lang.Thread.run(Thread.java:761)`

And I'm also seeing
`Google Play Services Library Error`  in the affected device in my One Signal project

![Screen Shot 2019-10-18 at 1 38 00 PM](https://user-images.githubusercontent.com/41004879/67068491-cf885c80-f1ac-11e9-970d-e5ada996cee5.png)

**Comment by rgomezp** [comment]
Please reach out to our support channel at OneSignal.com for faster help

**Comment by srdmnc** [comment]
Already did that @rgomezp , almost a week and this bug is still not resolved.

**Comment by srdmnc** [comment]
Additional Stacktrace

`[OneSignal] scheduleSyncServiceAsJob:result: 1
[OneSignal] GetUnsentActiveTime: 0
[OneSignal] SaveUnsentActiveTime: 2
[OneSignal] Unknown error getting FCM Token
[OneSignal] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getToken(java.lang.String, java.lang.String)' on a null object reference
[OneSignal] 	at com.onesignal.PushRegistratorFCM.getToken()
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration()
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle.access$100()
[OneSignal] 	at com.onesignal.PushRegistratorAbstractGoogle$1.run()
[OneSignal] 	at java.lang.Thread.run(Thread.java:760)`

**Comment by RafaelAraujo91** [comment]
I have the same issue here. @srdmnc , Did you find a solution?
