### ISSUE TITLE
NotificationExtenderService

### ISSUE THREAD

**Issue by rmenezes** [OneSignal/OneSignal-Xamarin-SDK#17]
I Can't find NotificationExtenderService on Xamarin SDK. Why?

**Comment by jkasten2** [comment]
@rmenezes We do not plan to the Mono runtime need to be loaded to process each notification. Please let us know your use case, we will consider adding it as part of the SDK.

In the meantime you will need to use `NotificationExtenderService` with native Java code on Android.

**Comment by rmenezes** [comment]
@jkasten2  in my situation, each time my application receives a push notification I need to verify some condition to play some alarm to get the attention of User. My application works with telemetry of energy.

**Comment by rmenezes** [comment]
@jkasten2 is there any workaround to me used in my situation?

**Comment by jkasten2** [comment]
@rmenezes Sorry but this part of your app will need to be in Java to process the notification before it is displayed.

**Comment by Osmosis311** [comment]
Is there any chance you will reconsider adding this to the Xamarin SDK?  Seems a bit arbitrary to not include core functionality, since you're already offering an SDK for Android.  Additionally, it's quite complicated to add a Java library to a Xamarin.Android project.
