### ISSUE TITLE
Not working with App was killed with Onesignal 3.6.0.

### ISSUE THREAD

**Issue by carl-neng** [OneSignal/OneSignal-Xamarin-SDK#175]
**Description:**

Before I have used onesignal 3.3.0 it working well but it have problem with iOS 13. can't subscription. But when I have update onesignal 3.3.0. to 3.6.0 it working on iOS. But I don't know how to implement background service for onesignal 3.6.0 I see they're include Xamarin.Firebase.Messaging.
 **So if you sample for implement this please help.**

**Environment**

Xamarin.Forms : 4.1.0.778454
Onsignal SDK : 3.6.0

**My Objective**
1. Just want to listening notification when app was killed.
2. Just want to handle notification when tap notification.

**Comment by rgomezp** [comment]
Howdy,
Please see our documentation on the [subject](https://documentation.onesignal.com/docs/silent-notifications). Note that sending background notifications requires writing native code. Cheers

**Comment by rgomezp** [comment]
Closing due to no response
