### ISSUE TITLE
Missing Google Play Services Library to All Registered Devices

### ISSUE THREAD

**Issue by santosh-3e** [OneSignal/OneSignal-Xamarin-SDK#180]
I am getting 

Missing Google Play Services Library
--

to my registered device. I am using com.OneSignal 3.7.1 , Xamarin.Forms 4.4.0.991537.

Please let me know what is the issue. 

Below is my androidmanifest file

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.OneSignalDemo.Android">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
  <permission android:name="com.companyname.OneSignalDemo.Android.permission.C2D_MESSAGE" android:protectionLevel="signature" />
  <uses-permission android:name="com.companyname.OneSignalDemo.Android.permission.C2D_MESSAGE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <application android:label="OneSignalDemo.Android">
    <receiver android:name="com.onesignal.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.companyname.OneSignalDemo.Android" />
      </intent-filter>
    </receiver>
  </application>
</manifest>

and Below is my App class

        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();

            OneSignal.Current.StartInit("cacd328a-1659-4cae-b250-c7ee2c0ed278")
             .EndInit();

        }

**Comment by santosh-3e** [comment]
I have changed my AndroidManifest.xml file as below to resolve above issue

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.OneSignalDemo.Android">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <permission android:name="com.companyname.OneSignalDemo.Android.permission.C2D_MESSAGE" android:protectionLevel="signature" />
  <uses-permission android:name="com.companyname.OneSignalDemo.Android.permission.C2D_MESSAGE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <application android:label="OneSignalDemo.Android">
    <receiver android:name="com.onesignal.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.companyname.OneSignalDemo.Android" />
      </intent-filter>
    </receiver>
  </application>
</manifest>

But now its showing error as 

No Push Token

for registered devices.

**Comment by rgomezp** [comment]
Hello @santosh-3e , 
If you are still seeing this issue, I recommend you reach out to our support channel over at onesignal.com

Cheers
