### ISSUE TITLE
silent notification doesnt work for android

### ISSUE THREAD

**Issue by omersezer** [OneSignal/OneSignal-Xamarin-SDK#184]
Silent notification does not work on android. On the onesignal side we set nil to android sound but android sound is still working. Then we set the EnableSound(false) android layer of our xamarin forms project. The sound is still working

**Comment by rgomezp** [comment]
Can you please include a code snippet where you are modifying the notification builder natively?

Is it possible another dependency is overriding any changes you are making to the builder?

**Comment by rgomezp** [comment]
Closing due to no response
