### ISSUE TITLE
UWP - Package SID

### ISSUE THREAD

**Issue by sviluppomania** [OneSignal/OneSignal-Xamarin-SDK#195]
Hi, in my UWP app I use OneSignal push notifications. Following their guide: https://documentation.onesignal.com/v5.0/docs/generate-a-windows-phone-package-sid-and-secret, I should insert the Package SID and the Client Secret, available in Microsoft Developer Center account, but in my app there is no longer the Windows Store platform where the Package SID was indicated. To make my notifications work where do I find it?

![image](https://user-images.githubusercontent.com/63558798/80830009-8350b700-8be8-11ea-861a-d57b84c232e0.png)

**Comment by rgomezp** [comment]
Howdy, 
You should be able to generate these keys from the [WNS Store Dashboard](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview).

**Comment by rgomezp** [comment]
Closing due to no response.
