### ISSUE TITLE
Can't install app after updating to 3.10.0

### ISSUE THREAD

**Issue by favosys** [OneSignal/OneSignal-Xamarin-SDK#209]
**Description:**

When we update the app to SDK 3.10.0 we are no longer able to install it on our test iPhones. This is Xamarin.Forms app built and signed using VS for Mac Professional v. 8.6.5 (build 23). The exact same app using OneSignal 3.8.2 or 3.9.0 works and installs fine.

**Environment**

1. What version of the Xamarin SDK are you using?
    3.10.0
2. How did you add the SDK to your project (eg. nuget)
    Nuget.org

**Steps to Reproduce Issue:**

1. In a Xamarin.Forms app, update OneSignal SDK to v. 3.10.0 in Main, Android and iOS projects
2. Build, archive as normal, sign as normal and produce AdHoc IPA file
3. Try to install IPA file on iPhone, it won't install
4. Upload IPA file to distribution platform, i.e. App Center, try to install build on test devices, it won't install

**Anything else:**

When trying to install, the app icon appears grayed out and it says the app can not be installed.

**Comment by rgomezp** [comment]
Howdy,
That's a very strange issue. Can you please include a logcat from the device? Thank you

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by favosys** [comment]
Thank you but I don't know how to get  Logcat if the app is not running, the app won't install

**Comment by rgomezp** [comment]
@favosys 
Take a look [here](https://documentation.onesignal.com/docs/troubleshooting-ios#how-to-get-a-crash-log-from-an-ios-device)

**Comment by rgomezp** [comment]
Closing due to no response
