### ISSUE TITLE
External user id is not being set

### ISSUE THREAD

**Issue by sledderGIT** [OneSignal/OneSignal-Xamarin-SDK#211]
**Description:**
External id is not being set sometimes. 
I do OneSignal.Current.StartInit(_configuration.OneSignalId).EndInit(); in the AppDelegates FinishedLaunching
then
OneSignal.Current.SetExternalUserId(id);
![image](https://user-images.githubusercontent.com/3392986/88392558-7e04a200-cdbc-11ea-9068-ec3415a67b16.png)
But no external user id is set.

**Environment**
1. Xamarin.iOS
2. Com.OneSignal for Xamarin 3.10.0 via nuget
3. iOS 13.5.1

**Steps to Reproduce Issue:**

1.  Add version 3.10.0 of the Xamarin SDK to your project
2. Initialize the SDK with your App ID
3. Set external user id in your App
4. Check Onesignal Users panel

**Comment by rgomezp** [comment]
Howdy,
Thanks for bringing this up. Would you please provide us with the logs from the device? Make sure you have set the OneSignal log level to VERBOSE. Cheers

**Comment by rgomezp** [comment]
Closing due to no response
