### ISSUE TITLE
How to block Onesignal push notifications on iOS(xamarin)?

### ISSUE THREAD

**Issue by FetFrumos** [OneSignal/OneSignal-Xamarin-SDK#212]
I use oneSignal in my xamarin app(for android and ios). I need to block some messages. I can make it on Android with NotificationExtenderService. by analogy i should use UNNotificationServiceExtension. But I don't know how to do it with this extension. Any advice.

**Comment by rgomezp** [comment]
Howdy,

Please follow our issue template and provide the full details or consider reaching out through our official support channel at OneSignal.com for these types of issues. Thank you.
