### ISSUE TITLE
Release stable version OneSignal nuget targeting AndroidX without Android.Support

### ISSUE THREAD

**Issue by PawKanarek** [OneSignal/OneSignal-Xamarin-SDK#213]
Please release stable version Onesignal nuget package targeting AndroidX without Android.Supports library, because new apps targeting Google Play sSore written in Xamrin.Forms should only contain AndroidX dependencies.

**Comment by jkasten2** [comment]
@PawKanarek We will be switching from the Android Support Library to AndroidX in the next major release (4.0.0).

In the meantime please include `Xamarin.AndroidX.Migration` if your project is using AndroidX.
https://github.com/xamarin/AndroidX/tree/master/source/migration

**Comment by Massimo37** [comment]
@jkasten2 is there a roadmap or approximate ETA on 4.0.0 ?

**Comment by deepakthumbmunkeys** [comment]
I also stuck with this, any news on this?

**Comment by AmirImam** [comment]
I have installed version 3.10.2, but notifications not showing. It returns **"recipients": 1** from REST calling, and successfully sent from test, either on emulator or real device. Is that because that version doesn't support androidx ?

**Comment by Jacko1394** [comment]
I'm stuck on this too,
Android X been out all year but can't update because of this dependency issue.
Unable to use OneSignal any longer because Google Play only accepts SDK 29 and higher now...

**Comment by AmirImam** [comment]
Now I am on version 3.10.3 with android 10 and still not working. No notifications show up. Please I want to know if my issue related to current issue

**Comment by ndastur** [comment]
Any news on this. Quite a critical issue now that Play Store reqiures a higher target build. Also been an issue on ONeSignal for a while now

**Comment by jkasten2** [comment]
I believe adding [Xamarin.AndroidX.Migration](https://github.com/xamarin/AndroidX/tree/master/source/migration) to your project should solve this issue in the short term.

For more details see the "Migration Tooling" section in this guide:
> 1. If your application includes **any dependencies that have not been migrated to the AndroidX namespace**, you’ll have to use our handy-dandy [Android Support Library to AndroidX Migration package.](https://www.nuget.org/packages/Xamarin.AndroidX.Migration)

https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/#migration-tooling

If not please provide any details or errors you are getting after adding `Xamarin.AndroidX.Migration` to your project.

**Comment by waseem852** [comment]
> I believe adding [Xamarin.AndroidX.Migration](https://github.com/xamarin/AndroidX/tree/master/source/migration) to your project should solve this issue in the short term.
> 
> For more details see the "Migration Tooling" section in this guide:
> 
> > 1. If your application includes **any dependencies that have not been migrated to the AndroidX namespace**, you’ll have to use our handy-dandy [Android Support Library to AndroidX Migration package.](https://www.nuget.org/packages/Xamarin.AndroidX.Migration)
> 
> https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/#migration-tooling
> 
> If not please provide any details or errors you are getting after adding `Xamarin.AndroidX.Migration` to your project.

Can not resolve reference: `Xamarin.Android.Support.Collections`, referenced by `Xamarin.GooglePlayServices.Base`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Collections`, or remove the reference to `Xamarin.GooglePlayServices.Base`

**Comment by ColdJackle** [comment]
I have reached out to the support a month ago and this still hasn't been resolved. They said that they are aware of these threads, but nothing happened so far. Except for (and correct me if I'm wrong), but the [native SDK](https://github.com/OneSignal/OneSignal-Android-SDK) seems to have already been updated to use AndroidX. But the Xamarin version is way behind.

I have clients waiting for an update, but this issue keeps me from even using the project solution right now. Does anyone have a workaround? A fork maybe?

**Comment by tagathangelou** [comment]
Hi I have the same issue - My VS is fully updated, all nuget packages are fully updated to the most stable version and once i install the ONESIGNAL nuget package i get the following error when i try to build my solution:

**_Can not resolve reference: `Xamarin.Android.Support.Collections`, referenced by `Xamarin.GooglePlayServices.Base`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Collections`, or remove the reference to `Xamarin.GooglePlayServices.Base`._**

I send a message yesterday to support and still nobody answered me.  I suspect is something not compatible with .NET standard version 2.0.3 and ONESIGNAL and VS does not allow you to go to a previous version of .NET STANDARD once NESIGNAL is installed since probably is required by ONESGNAL

Anyone found a solution for this... it looks i might start considering moving to another service since its the second day i am stuck

thanks
Tassos

**Comment by jkasten2** [comment]
We just released [Com.OneSignal 3.10.5](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.10.5) with dependency changes to resolve the AndroidX compatibility. Simply upgrade to this version and rebuild your project.
