### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by rcouch00** [OneSignal/OneSignal-Xamarin-SDK#218]
**Description:**

1) Open Example.Shared.Application in Xamarin

* I can only assume you mean open OneSignal.sln with visual studio (for mac)

2) In the Android project's AndroidManifest.xml, Replace "EDIT_APPID_TO_TEST_THIS_APP" with your OneSignal Application ID.

* command shift F -> paste string -> 0 results in 148 files 

3) Replace "EDIT_GPN_TO_TEST_THIS_APP" with your Google Project Number.

* command shift F -> paste string -> 0 results in 148 files 

4) In the iOS project's Info.plist replace "EDIT_APPID_TO_TEST_THIS_APP" with your OneSignal Application ID.

* command shift F -> paste string -> 0 results in 148 files 

5) Build and deploy applications to your devices and send a test notification via the OneSignal dashboard.

* this builds, but its completely wrong to deploy for a test and invalid setup instructions.

**Environment**

=== Visual Studio Community 2019 for Mac ===
Version 8.7.6 (build 2)
Installation UUID: 63839b37-3150-420f-804d-05c15226613e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 612000093
=== Mono Framework MDK ===
Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093
=== Roslyn (Language Service) ===
3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
=== NuGet ===
Version: 5.7.0.6702
=== .NET Core SDK ===
SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Version: 3.1.402
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks
=== .NET Core Runtime ===
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	2.1.22
=== Xamarin.Profiler ===
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
=== Updater ===
Version: 11
=== Apple Developer Tools ===
Xcode 11.7 (16142)
Build 11E801a
=== Xamarin.Mac ===
Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400
=== Xamarin.Android ===
Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/test/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2
Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f
=== Microsoft OpenJDK for Mobile ===
Java SDK: /Users/test/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
=== Android SDK Manager ===
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC
=== Android Device Manager ===
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC
=== Xamarin.iOS ===
Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400
=== Xamarin Designer ===
Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC
=== Build Information ===
Release ID: 807060002
Git revision: f69dff5c1e88ec0d76d7fab567c69339ef02862b
Build date: 2020-09-09 04:56:43-04
Build branch: release-8.7
Xamarin extensions: f69dff5c1e88ec0d76d7fab567c69339ef02862b
=== Operating System ===
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

**Steps to Reproduce Issue:**

1. install visual studio for mac (8.7.6) (everything, install it all)
1.  clone onesignal xamarin sdk repo
1. open solution file
1. wait for project restore from nuget
1.  attempt to follow readme sample project instructions
**Anything else:**

(crash stacktraces, as well as any other information here)

can't get that far, it does build..but..

* isn't being signed (no instructions for that)
* can't deploy to a device (isn't signed)
* can't run in an emulator (push)
* where do I plug in the onesignal app_id?

**Comment by rgomezp** [comment]
Howdy,
Please follow our setup [instructions here](https://documentation.onesignal.com/docs/xamarin-sdk-setup).

Thank you
