### ISSUE TITLE
Background notification

### ISSUE THREAD

**Issue by noon974** [OneSignal/OneSignal-Xamarin-SDK#22]
Hi, 

I'm trying to implement OneSignal push notification on a Xamarin Forms PCL solution.
I'm currently receiving notifications on the Android project when the app is started (foreground, and background)
As soon as I close the app (removing it from "recent app"), I do not receive push notifications anymore. 
I can see on Xamarin's forum that there is need to have a "Broadcast Receiver" to get notification when app is closed, but there is no mention to this in your setup tutorial on OneSignal website.
Any info on this  ?

**Comment by noon974** [comment]
Well, it seems that EMUI was my main issue regarding this. After adding the app to authorized app to override battery saving, the notification are now correctly received even when the app is closed.
I still had to add IntentService to the AndroidManifest.xml, this should be on the setup tutorial thought.

**Comment by ndastur** [comment]
@noon974 could you elaborate on what exactly needs to be added to the AndroidManifest . Ty

**Comment by noon974** [comment]
Check the sample project to get more information on this, I don't have the code right now.

**Comment by jkasten2** [comment]
@ndastur @noon974 is referring the `BroadcastReceiver` noted in step 3.2 in our newest setup guide.

https://documentation.onesignal.com/docs/xamarin-sdk-setup#section-3-android-setup
