### ISSUE TITLE
Notification Images Not Showing only in iOS

### ISSUE THREAD

**Issue by MarcinBacic** [OneSignal/OneSignal-Xamarin-SDK#229]
**Description:**
Images are not displayed when notifications with photos are sent. I check https://documentation.onesignal.com/docs/notification-images-not-showing

**Environment**

1. Use  OneSignal 3.10.4 of the Xamarin SDK
1. Iphone 8 version 14.4

**Steps to Reproduce Issue:**
1. Add version  OneSignal 3.10.4 of the Xamarin SDK to your project
1. Use Com.OneSignal.Sample.iOS app
1. Attempt to receive a push notification  with image https://cdn.pixabay.com/photo/2018/01/21/01/46/architecture-3095716_960_720.jpg
 ![image](https://user-images.githubusercontent.com/79567871/108967535-f21f6500-767f-11eb-8a3b-365ffc9c59ff.png)
1. Receipt of notification without photo
 ![image](https://user-images.githubusercontent.com/79567871/108972893-0e250580-7684-11eb-827e-cb79e520f45d.png)

**Comment by jkasten2** [comment]
@MarcinBacic I recommend double checking ["5. iOS - Add the Notification Service Extension"](https://documentation.onesignal.com/docs/xamarin-sdk-setup#5-ios---add-the-notification-service-extension) to make sure this is setup correctly as it is required for image and action buttons to work on iOS notifications.

If the above is correct I also recommend following the ["Troubleshooting the iOS Notification Service Extension"](https://documentation.onesignal.com/docs/service-extensions#troubleshooting-the-ios-notification-service-extension) steps.
