### ISSUE TITLE
Cannot build the Solution on VISUAL STUDIO when installing  ONESIGNAL 3.10.4 NUGET PACKAGE

### ISSUE THREAD

**Issue by tagathangelou** [OneSignal/OneSignal-Xamarin-SDK#230]
**Description:**

My VS is fully updated, all nuget packages are fully updated to the most stable version and once i install the ONESIGNAL nuget package i get the following error when i try to build my solution:

Can not resolve reference: Xamarin.Android.Support.Collections, referenced by Xamarin.GooglePlayServices.Base. Please add a NuGet package or assembly reference for Xamarin.Android.Support.Collections, or remove the reference to Xamarin.GooglePlayServices.Base.
**Environment**
1.My Android version Target framework is 10.0

1. Visual studio 2019 fully updated
1. NET STANDARD LIBRARY - latest stable version - basically all nuget packages are fully updated
1. installed onesignal latest stable version 3.10.4 via nuget package
![target framework android](https://user-images.githubusercontent.com/6680836/113123934-ab440280-921d-11eb-8886-35dc78f6ebb9.JPG)

**Steps to Reproduce Issue:**

1. Add onesignal nuget package 3.10.4
1. Try to build the app and receive the error:

![error build app after installing onesignal](https://user-images.githubusercontent.com/6680836/113123963-b39c3d80-921d-11eb-84af-3c403ca96814.JPG)

**My INSTALLED PACKAGES ARE:**
![installed nugetpackages](https://user-images.githubusercontent.com/6680836/113124618-5fde2400-921e-11eb-82ca-a68811fe3bcf.JPG)

![installed nugetpackages 2](https://user-images.githubusercontent.com/6680836/113124652-68cef580-921e-11eb-8e5f-75e1a30b4323.JPG)

**My Visual Studio version:**

![vs2019](https://user-images.githubusercontent.com/6680836/113124815-987dfd80-921e-11eb-9fc3-3ccf48b96b75.JPG)

**Comment by tagathangelou** [comment]
Anybody with a solution to this? 

Onesignal contacted me and told me to install **_Xamarin.AndroidX.Migration_** to my project should solve this issue in the short term while will work on a solution.

That solution does not work for me and the problem remains exactly the same.

**Comment by JigarM** [comment]
@tagathangelou Facing the same issue. Even I tried the solution which you have mentioned but still facing the same issue.

**Comment by tmijieux** [comment]
apart from onesignal, I am not using firebase, but i have no problems using onesignal at the moment (even alongside androidx) with the following dependencies: 
(but maybe keeping your firebase packages as they are may be pose conflicts with some of these packages ?)

```
    <PackageReference Include="CClarke.Plugin.Calendars" Version="1.0.14" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.0" />
    <PackageReference Include="Xam.Plugin.Media" Version="5.0.1" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.GooglePlayServices.Base" Version="71.1610.1" />
    <PackageReference Include="Xamarin.GooglePlayServices.Tasks" Version="71.1601.1" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.OpenId.AppAuth.Android" Version="0.7.0" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources" Version="1.1.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.3.0.5" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.7" />
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.Annotations" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.Compat" Version="28.0.0.3" />
```

**Comment by JigarM** [comment]
@jkasten2  I have applied the solution mentioned in below URL and it works fine now.
https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/228#issuecomment-813979825

Thanks

**Comment by jkasten2** [comment]
We just released [Com.OneSignal 3.10.5](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.10.5) with dependency changes solve the AndroidX compatibility. Simply upgrade to this version and rebuild your project.

**Comment by tagathangelou** [comment]
Thanks for releasing the solution with the new version 3.10.5 - i already rebuild and it connects smoothly retrieving the device player ID
