### ISSUE TITLE
Pushs does not works after device is restarted

### ISSUE THREAD

**Issue by YordanYanakiev** [OneSignal/OneSignal-Xamarin-SDK#24]
Hello.
Once the devices is restarted or application terminated the pushes never been received.

**Comment by jkasten2** [comment]
@YordanYanakiev Some Android device's put the your app in to a force closed state after the device is restarted. See the `The app is Force Stopped` section on the page below for more details on this.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by jkasten2** [comment]
@YordanYanakiev Feel free to response with more details if you are still having an issue and we can reopen this issue.
