### ISSUE TITLE
com.onesignal.OneSignalDbHelper.getSQLiteDatabase 

### ISSUE THREAD

**Issue by ValonK** [OneSignal/OneSignal-Xamarin-SDK#242]
**Description:**

i am getting the following Crash report from our Users

Stacktrace

```
com.onesignal.OneSignalDbHelper.getSQLiteDatabase
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1034 SQLITE_IOERR_FSYNC)

android.database.sqlite.SQLiteConnection.nativeExecute SQLiteConnection.java
android.database.sqlite.SQLiteConnection.execute SQLiteConnection.java:709
android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration SQLiteConnection.java:462
android.database.sqlite.SQLiteConnection.open SQLiteConnection.java:263
android.database.sqlite.SQLiteConnection.open SQLiteConnection.java:205
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked SQLiteConnectionPool.java:505
android.database.sqlite.SQLiteConnectionPool.open SQLiteConnectionPool.java:206
android.database.sqlite.SQLiteConnectionPool.open SQLiteConnectionPool.java:198
android.database.sqlite.SQLiteDatabase.openInner SQLiteDatabase.java:919
android.database.sqlite.SQLiteDatabase.open SQLiteDatabase.java:899
android.database.sqlite.SQLiteDatabase.openDatabase SQLiteDatabase.java:763
android.database.sqlite.SQLiteDatabase.openDatabase SQLiteDatabase.java:752
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked SQLiteOpenHelper.java:373 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase SQLiteOpenHelper.java:316
com.onesignal.OneSignalDbHelper.getSQLiteDatabase
com.onesignal.OneSignalDbHelper.getSQLiteDatabaseWithRetries
com.onesignal.OneSignalDbHelper.delete
com.onesignal.OneSignalCacheCleaner.cleanCachedNotifications
com.onesignal.OneSignalCacheCleaner.access$000
com.onesignal.OneSignalCacheCleaner$1.run
java.lang.Thread.run Thread.java:920

```

**Environment**

Com.OneSignal **3.10.5**
Xamarin.Forms **4.8.0.1451**

Android 12 
Pixel 4XL

**Steps to Reproduce Issue:**

At the moment I cannot Repro this Issue, will update the Issue if I manage to do so.

**Comment by jkasten2** [comment]
@ValonK Thanks for reporting with the stacktrace and providing device details. Can you also let us know the number of crashes and users / devices with this issue?

**Comment by ValonK** [comment]
![image](https://user-images.githubusercontent.com/23531499/129871125-0dd96396-92eb-466d-b581-36fab9e42ac0.png)
![image](https://user-images.githubusercontent.com/23531499/129871198-ed13c25b-f269-45ad-a9e7-640567670fed.png)

**Comment by tanaynigam** [comment]
@ValonK closing the issue for now. Please test the issue on our latest release [OneSignalSDK.Xamarin-4.0.0](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0) and re-open the issue if it still exists.

Please note that we have changed the package name and namespace for the SDK from `Com.OneSignal` to `OneSignalSDK.Xamarin` and would require you to remove the previous package name and add the new package name to import the SDK in your code.

Additionally, when searching for the package on nuget.org, you will be required to search for [OneSignalSDK.Xamarin](https://www.nuget.org/packages/OneSignalSDK.Xamarin/4.0.0) to import the package
