### ISSUE TITLE
OneSignal Xamarin SDK Version 4 - Now available!

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#262]
# Description
The OneSignal Xamarin major release version 4 is now in **Available**!

This version includes many exciting changes including an overall simplification of the API as well as many of the underlying native improvements and bug fixes.

Some key changes:
* Foreground Notification Control API allows you to control the display of a notification based on application foreground status.
* Simplified APIs by providing useful defaults for function calls and removing deprecated code; now, code completions should be less cluttered.
* Android apps get better compatibility with other 3rd-party libraries by upgrading to AndroidX libraries.
* And all the other latest features from Android SDK v4.6.3 and iOS SDKs v3.9.1.

## Migration guide
See our [Step-by-Step Xamarin 3.x to 4.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-xamarin-3x-to-400-upgrade-guide) to get started!

## Why you should start migrating now
Most importantly, we want to give you the opportunity to voice your opinion and provide feedback so that we can make changes as needed to better suit your implementation.

Furthermore, it is always beneficial to get a head start on migrating your implementation to ensure a smooth transition. As we continue improving OneSignal, being fully migrated to the latest version of the SDK will help minimize potential issues and ensure you can focus on providing value to your customers, improving your business, and creating a delightful messaging experience.

To begin migrating your app to version 4, read our migration guide [**here**](https://documentation.onesignal.com/docs/step-by-step-xamarin-3x-to-400-upgrade-guide). Regarding this guide, please let us know if anything could be clarified or communicated better.

[Releases Page](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases)

We are looking forward to hearing from you.

**Comment by jeremymarabel** [comment]
Hi, i have an issue with Xamarin.Forms on iOS.

Android is working fine, but on iOS I have this error when building on simulator and real device :
`>/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(141,3): Error  : /Users/[REDACTED]/iOS/bin/iPhoneSimulator/Debug/Com.OneSignal.iOS.resources/OneSignal.xcframework has an incorrect or unknown format and cannot be processed.`

I also tested just adding the package to a blank xamarin.forms project and got the same result

**Comment by jkasten2** [comment]
@jeremymarabel Could you let us know the Xamarin version and Visual Studio version you are using? Could you share your blank project where you reproduced the error?

**Comment by EmilAlipiev** [comment]
Most important is can you please confirm that no "Admob" reference within the dependencies?

**Comment by skir** [comment]
I have the same `OneSignal.xcframework has an incorrect or unknown format and cannot be processed` error on newly released 4.0.0-beta2 in my Xamarin.iOS project.

**Comment by jkasten2** [comment]
@EmilAlipiev I can confirm no ads references whatsoever in the the list of dependencies for 4.0.0. See the nuspec file here:
https://github.com/OneSignal/OneSignal-Xamarin-SDK/blob/4.0.0_release/Com.OneSignal.nuspec

**Comment by jkasten2** [comment]
We have reproduce and have a working fix for the `OneSignal.xcframework has an incorrect or unknown format and cannot be processed` error. We will be shipping a beta3 in the next few days so you can continue testing your iOS integration.

**Comment by jkasten2** [comment]
@EmilAlipiev Thanks for trying out the beta, is this issue only happening on Android?
If you uninstall then reinstall the app on the device is it register successfully for push?
Can you try enabling Verbose OneSignal logging and share the log?

**Comment by jkasten2** [comment]
@skir @jeremymarabel We fixed the XCFramework issue you were seeing in beta3. Try it out and let us know how it goes.

**Comment by ronmichael** [comment]
Testing 4.0.0beta4 using Visual Studio 2022 and a physical device. I do have a notification service extension in the solution. Everything works -- until I add delegates for NotificationWillShow or NotificationWasOpened. Then the app crashes. Debugger just returns a useless null exception error back up to Main.

**Comment by ronmichael** [comment]
Oh, and the extension doesn't appear to ever be called. I was having this problem with 3.x though too.

**Comment by EmilAlipiev** [comment]
Is ios still using admob on 4.00beta4? I get this [error ](https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc)on simulator and this issue is normally caused by admob which i dont use directly but only Onesignal

**Comment by jmadler** [comment]
There's no AdMob dependency in any OneSignal SDK.  Can you please file a bug with the specific issue you're seeing, if you think it may be related to our SDK?

**Comment by Poker26-8** [comment]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		android:exported needs to be explicitly specified for element <receiver#com.onesignal.GcmBroadcastReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.	TELEMETRIA.Android	C:\6\XAMARIN\Nueva carpeta\TELEMETRIA\TELEMETRIA\TELEMETRIA\TELEMETRIA.Android\obj\Debug\130\AndroidManifest.xml	19	


al exportarlo para instalarlo al teléfono real manda ese error

**Comment by Poker26-8** [comment]
alguien sabe como solucionarlo

**Comment by Cvijo** [comment]
your link [step-by-step-xamarin-3x-to-400-upgrade-guide](https://documentation.onesignal.com/docs/step-by-step-xamarin-3x-to-400-upgrade-guide) is broken, i am not able to follow any guide
