### ISSUE TITLE
Rare crash when opening notification on Android

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#27]
Crash from OneSignal Xamarin SDK 2.1.1. Issue seems to be Android version independent as this was reported from 4.1 to 6.0 devices. Nor does is it manufacture specific.

Issue may be related to the payload of the notification as this hasn't been reproduced on a test device.

```Java
OneSignalAndroid.OSNotificationToNative
   Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
   Com.OneSignal.OneSignalAndroid.OSNotificationToNative(OSNotification notif)<fea9caad470e4df8a9fb405ec27f159d>:0
   Com.OneSignal.OneSignalAndroid.OSNotificationOpenedResultToNative(OSNotificationOpenResult result)<fea9caad470e4df8a9fb405ec27f159d>:0
   Com.OneSignal.OneSignalAndroid.NotificationOpenedHandler.NotificationOpened(OSNotificationOpenResult result)<fea9caad470e4df8a9fb405ec27f159d>:0
   Com.OneSignal.Android.OneSignal.INotificationOpenedHandlerInvoker.n_NotificationOpened_Lcom_onesignal_OSNotificationOpenResult_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0)<3a06eb26aacb4aa290fb07c397112065>:0
   at (wrapper dynamic-method) System.Object:d5b26ac2-e2ff-4461-8029-eebaf213382f (intptr,intptr,intptr)
   md535652bf13383ade65ac6494a9e050955.OneSignalAndroid_NotificationOpenedHandler.n_notificationOpened(Native Method)
   md535652bf13383ade65ac6494a9e050955.OneSignalAndroid_NotificationOpenedHandler.notificationOpened()OneSignalAndroid_NotificationOpenedHandler.java:30

   com.onesignal.OneSignal.fireNotificationOpenedHandler()OneSignal.java:1009
   com.onesignal.OneSignal.runNotificationOpenedCallback()OneSignal.java:954
   com.onesignal.OneSignal.fireCallbackForOpenedNotifications()OneSignal.java:422
   com.onesignal.OneSignal.init()OneSignal.java:301
   md516d7c29277aa534b649714005ae22ea3.MainActivity.n_onCreate(Native Method)
   md516d7c29277aa534b649714005ae22ea3.MainActivity.onCreate()MainActivity.java:33
   android.app.Activity.performCreate()Activity.java:5372
   android.app.Instrumentation.callActivityOnCreate()Instrumentation.java:1104
   android.app.ActivityThread.performLaunchActivity()ActivityThread.java:2257
   android.app.ActivityThread.handleLaunchActivity()ActivityThread.java:2349
   android.app.ActivityThread.access$700()ActivityThread.java:159
   android.app.ActivityThread$H.handleMessage()ActivityThread.java:1316
   android.os.Handler.dispatchMessage()Handler.java:99
   android.os.Looper.loop()Looper.java:176
   android.app.ActivityThread.main()ActivityThread.java:5419
   java.lang.reflect.Method.invokeNative(Native Method)
   java.lang.reflect.Method.invoke()Method.java:525
   com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1046
   com.android.internal.os.ZygoteInit.main()ZygoteInit.java:862
   dalvik.system.NativeStart.main(Native Method)
```

**Comment by ndastur** [comment]
I think this is a Xamarin Forms activity lifecycle problem. Try setting launch mode to SingleTask

**Comment by falox** [comment]
@ndastur SingleTask launch mode didn't fix.

**Comment by ndastur** [comment]
@falox sorry to hear that. I has sorted out our issue.
Just to check you have set ```LaunchMode = LaunchMode.SingleTask,``` in MainActivity.cs of your droid project

**Comment by falox** [comment]
Thanks @ndastur, but I can confirm I'm still getting the error even with `LaunchMode.SingleTask` in MainActivity.cs.

**Comment by falox** [comment]
The only way I've found to avoid the problem is to add a generic `try/catch` in the [OSNotificationToNative()](https://github.com/OneSignal/OneSignal-Xamarin-SDK/blob/e3c019670c5de6b473ec40d52dce295dc97504bb/Com.OneSignal.Android/NotificationOpenedHandler.cs#L34) function:

<pre>
// this version works
public static OSNotification OSNotificationToNative(Android.OSNotification notif)
{
	<b>try
	{</b>		
		var notification = new OSNotification();
		:
		return notification;
	<b>} 
	catch
	{
		return null;
	}</b>
}
</pre>

I know this is not ideal. Previously I've added some null checks, but with no success:

<pre>
// this version still throws the exception
public static OSNotification OSNotificationToNative(Android.OSNotification notif)
{
	<b>if (notif == null)
	{
		return null;
	}</b>

	var notification = new OSNotification();
	notification.shown = notif.Shown;
	notification.androidNotificationId = notif.AndroidNotificationId;
	notif.GroupedNotifications = notif.GroupedNotifications;
	notif.IsAppInFocus = notif.IsAppInFocus;

	notification.payload = new OSNotificationPayload();

	notification.payload.actionButtons = new List<Dictionary<string, object>>();
	if (<b>notif.Payload != null &&</b> notif.Payload.ActionButtons != null)
	{
		foreach (Android.OSNotificationPayload.ActionButton button in notif.Payload.ActionButtons)
		{
			<b>if (button != null)
			{</b>
				var d = new Dictionary<string, object>();
				d.Add(button.Id, button.Text);
				notification.payload.actionButtons.Add(d);
			<b>}</b>
		}
	}

	notification.payload.additionalData = new Dictionary<string, object>();
	if (<b>notif.Payload != null &&</b> notif.Payload.AdditionalData != null)
	{
		var iterator = notif.Payload.AdditionalData.Keys();
		while (iterator.HasNext)
		{
			var key = (string)iterator.Next();
			notification.payload.additionalData.Add(key, notif.Payload.AdditionalData.Get(key));
		}
	}

	notification.payload.body = notif.Payload.Body;
	notification.payload.launchURL = notif.Payload.LaunchURL;
	notification.payload.notificationID = notif.Payload.NotificationID;
	notification.payload.sound = notif.Payload.Sound;
	notification.payload.title = notif.Payload.Title;
	notification.payload.bigPicture = notif.Payload.BigPicture;
	notification.payload.fromProjectNumber = notif.Payload.FromProjectNumber;
	notification.payload.groupMessage = notif.Payload.GroupKey;
	notification.payload.groupMessage = notif.Payload.GroupMessage;
	notification.payload.largeIcon = notif.Payload.LargeIcon;
	notification.payload.ledColor = notif.Payload.LedColor;
	notification.payload.lockScreenVisibility = notif.Payload.LockScreenVisibility;
	notification.payload.smallIcon = notif.Payload.SmallIcon;
	notification.payload.smallIconAccentColor = notif.Payload.SmallIconAccentColor;

	return notification;
}
</pre>

Since from the stack I cannot see which line is throwing the exception, I just made some guesses looking at the code. I see other points to check, but I didn't test them for time constraints.

I then added the generic try/catch and the crash reports disappeared from HockeyApp.

@jkasten2 How about to add the try/catch in the master until there are additional info for a better fix?

**Comment by Nightsd01** [comment]
I believe this issue has been resolved as I've been unable to reproduce it. If anyone encounters this issue again please post on here and I'll be happy to reopen + investigate.
