### ISSUE TITLE
One Signal Migration from 3.x to 4.x - Class Crashed.

### ISSUE THREAD

**Issue by Drzeww** [OneSignal/OneSignal-Xamarin-SDK#296]
Description:

Hello.
Yesterday i decided to target my applications to Android 12+, setted all "android exported" but got the issue on one signal old version 3x+, and the only way was to migrate to 4x+ but sadly it ruined my Push Notification activity.

The problem is about 2 imports which are no longer exist in 4x+ one signal, i found some guide here, https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide , but but when i tryed to replace NotificationExtenderService to OSRemoteNotificationReceiveHandler SDK wont find it.

Here s my non compatible class to 4x+ migration, have you guys any idea to fix these 2 imports and code?

https://pastebin.com/iM40F8hx

Environment
I am using 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.4, 0.99.99]'

Steps to Reproduce Issue:
Update the One Signal from 3.x to 4.x by using class above.

And here s screenshot how it looks like in android studio.
https://i.imgur.com/l8Fgyrz.png

Thanks for any help.

**Comment by jkasten2** [comment]
@Drzeww Thanks for reporting and sharing you code. "NotificationExtenderService" has been renamed to  "NotificationServiceExtension" which includes a new method name and a different setup via the `AndroidManifest.xml`.
See [Background Notification Control](https://documentation.onesignal.com/docs/40-api-android-native#background-notification-control) to migrate to this.
