### ISSUE TITLE
Success and failure delegate can't be set for PostNotification

### ISSUE THREAD

**Issue by ndastur** [OneSignal/OneSignal-Xamarin-SDK#31]
Prior to the new NuGet package I used:

`
OneSignal.Current.PostNotification(notification, (responseSuccess) =>
{
Debug.WriteLine("Notification posted successfully!.\n" + Json.Serialize(responseSuccess));
}, (responseFailure) =>
{
Debug.WriteLine("Notification failed to post:\n" + Json.Serialize(responseFailure) );
});
`

to send a notification. But now there is no method with 3 arguments exposed. Looking at the source the 3 arg method is still there and marked as public but can't be accessed.

BTW I have just `using Com.OneSignal;` at the top

**Comment by jkasten2** [comment]
@ndastur The was missed in the 3.0 release. We will make sure the callbacks get added in the next release.

**Comment by ndastur** [comment]
Hi Guys. Sorry but error handling is fairly vital to any app. This is something that just has to be done please. It been 7 months now

**Comment by ndastur** [comment]
@jkasten2 sorry but for such a simple fix this has been far too long. My assumption is that this project is dead. Bye guys, so long and thanks for all the fish ...

**Comment by jkasten2** [comment]
This is now fixed in the latest [OneSignal Xamarin 3.1.0 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.1.0)!
