### ISSUE TITLE
Upgrade nuget

### ISSUE THREAD

**Issue by pierrebrito** [OneSignal/OneSignal-Xamarin-SDK#310]
The version available on nuget is still in beta.
https://www.nuget.org/packages/Com.OneSignal/4.0.0-beta4

**Comment by jkasten2** [comment]
@pierrebrito We ended up changing the name of the package from `Com.OneSignal` to `OneSignalSDK.Xamarin` before the final 4.0.0 release. See the full release notes for more details:
https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0

We will mark the `Com.OneSignal` deprecated and point to `OneSignalSDK.Xamarin` so the migration isn't missed.
