### ISSUE TITLE
[iOS] Migrating to 4.1.0 throws copy error with Headers (.h)

### ISSUE THREAD

**Issue by vincentcastagna** [OneSignal/OneSignal-Xamarin-SDK#316]
**Description:**

Migrated from 3.1.6 to latest 4.1.0. 
Now when building the project I face an odd issue. Tried of course to rebuild, clear bin&obj etc ... 

> 5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 1 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 2 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 3 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 4 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 5 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 6 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 7 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 8 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 9 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): warning MSB3026: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Beginning retry 10 in 1000ms. Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): error MSB3027: Could not copy "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Exceeded retry count of 10. Failed. 
5>C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): error MSB3021: Unable to copy file "C:\Users\casta\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h" to "D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h". Could not find a part of the path 'D:\DEVELOPPEMENT\MP\PrivateFront\Private\Private.iOS\bin\iPhone\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalExtension.xcframework\ios-arm64_i386_x86_64-simulator\OneSignalExtension.framework\Headers\OneSignalNotificationServiceExtensionHandler.h'.

**Environment**

OneSignalSDK : 4.1.0
Xamarin Forms : 5.0
Visual Studio : 2022 - 17.2.5 
Target Framework : iOS 15.4 

**Steps to Reproduce Issue:**

1. Use VS 17.2.5 
2. Use Xamarin SDK 4.1.0
3. Build project . 

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by vincentcastagna** [comment]
Now that I saw the other issue, might be related to #312

**Comment by developer9969** [comment]
@vincentcastagna  spent all day on it and does not work on iOS but does in android. I hope they fix it as we are stuck

**Comment by vincentcastagna** [comment]
This sounds like a possible issue with the Xamarin Binding of the one signal library, as the error includes the xcframework headers (.h).

For now I'll just downgrade to 4.0.0 as this version doesn't have the error.

**Comment by developer9969** [comment]
@vincentcastagna  thanks - totally agree, lets hope is not a long wait
