### ISSUE TITLE
[iOS][4.1.0] Unable to compile / OneSignalTrackFirebaseAnalytics.h not found

### ISSUE THREAD

**Issue by twelve-cgn** [OneSignal/OneSignal-Xamarin-SDK#319]
**Description:**

When trying to migrate from 3.x to 4.1.0 i'm unable to compile iOS.
I get the following errors (see StackTrace)

**Environment**

XForms 5.0.0.2478
OneSignalSDK.Xamarin 4.1.0 (NuGet)

**Anything else:**

4>  C:\Users\xxx\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): error MSB3027: "C:\Users\xxx\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalCore.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalCore.framework\Versions\A\Headers\OneSignalTrackFirebaseAnalytics.h" konnte nicht in "C:\Workspaces\xxx\BusPro.NET-Connect\BusProNet.App\BusProNet.App.iOS\bin\iPhoneSimulator\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalCore.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalCore.framework\Versions\A\Headers\OneSignalTrackFirebaseAnalytics.h" kopiert werden. Die zulässige Anzahl von Wiederholungen von 10 wurde überschritten. Fehler. 
4>  C:\Users\xxx\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\OneSignalSDK.Xamarin.targets(6,9): error MSB3021: Die Datei "C:\Users\xxx\.nuget\packages\onesignalsdk.xamarin\4.1.0\build\Xamarin.iOS\..\..\content\OneSignalSDK.Xamarin.iOS.resources\OneSignalCore.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalCore.framework\Versions\A\Headers\OneSignalTrackFirebaseAnalytics.h" kann nicht in "C:\Workspaces\xxx\BusPro.NET-Connect\BusProNet.App\BusProNet.App.iOS\bin\iPhoneSimulator\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalCore.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalCore.framework\Versions\A\Headers\OneSignalTrackFirebaseAnalytics.h" kopiert werden. Ein Teil des Pfades "C:\Workspaces\xxx\BusPro.NET-Connect\BusProNet.App\BusProNet.App.iOS\bin\iPhoneSimulator\Debug\/OneSignalSDK.Xamarin.iOS.resources/OneSignalCore.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalCore.framework\Versions\A\Headers\OneSignalTrackFirebaseAnalytics.h" konnte nicht gefunden werden.

**Comment by jkasten2** [comment]
@twelve-cgn Thanks for reporting. We are fixing in an upcoming update, we will let you know the exact version when it releases.
