### ISSUE TITLE
Can't determine programmatically if init fails

### ISSUE THREAD

**Issue by ndastur** [OneSignal/OneSignal-Xamarin-SDK#32]
There doesn't seem to be any error reporting for a failed Init(). I have tried surrounding the StartInit() call in try ... catch ... but no exception is thrown and there isn't a success / failure return or delegate.

I ask as if registration with the onesignal server fails I'd like to be able to retry again after a period of time. Unless this happens in the SDK already??

**Comment by jkasten2** [comment]
@ndastur Our Android SDK will automatically retry so you don't need to handle this.

iOS itself automatically handles APNs connection issues to get the push token. Then as soon as our SDK receives it we sent it off to our OneSignal server. We don't have automatic retries in place if the call fails to our server but this would be very rare as the device would have to be online at the time the pushToken is received. We do retry when the user comes back to your app, however we are looking into adding additional retries while the app is running in future updates.

You can call the OneSignal `IdsAvailable` method to know if the user accepted notifications and is subscribed by checking if the `pushToken` is not `null`.

**Comment by ndastur** [comment]
@jkasten2 ty. It was connection to your servers I was talking about. Unfortunately in mobile apps this can be quite a common scenario.

Init is done on app opening and if there is no data signal then the connection to onesignal fails. Try it yourself by putting phone in flight mode and opening an app.

**Comment by jkasten2** [comment]
Which platform (iOS or Android) are you seeing an issue with?

We are looking into provide better handle for iOS. Also we will be providing a more detail response for the current subscription status other than idsAvaialble.

**Comment by ndastur** [comment]
I've only noticed on ios.

**Comment by jkasten2** [comment]
@ndastur iOS also has retrying built into the SDK with the 3.1.1 release as it's core native iOS SDK has been updated to the latest version. No retrying is need by your app's code for either Android or iOS. Marking this issue as resolved
