### ISSUE TITLE
Unable to Compile and Test 4.2.0 Beta - MAUI

### ISSUE THREAD

**Issue by excellapay** [OneSignal/OneSignal-Xamarin-SDK#329]
In VS 2022 Preview on Mac and Windows (latest)

**Description:**
Opening the project, I immediately get a few notices about the build settings on Windows. The panel where you set Debug / Release and All CPU.  Then when trying to run, it is not happy with the Android Manifest.xml file.  Looks like the the target and min versions are not right. I am unable to find a good combination. 

(your description here)

**Environment**
This is just a simple download of the 4.2.0-beta1-maui codeline and upzip it. 

Issues on Mac are all related to the Android code but preventing the app from fully building.  Has anyone had issue or success on this beta code?

**Comment by fhboswell** [comment]
@excellapay We are working on resolving issues with our MAUI support.

**Comment by fhboswell** [comment]
Hello @excellapay We now have MAUI / .Net 6 support. Please see our new [Nuget](https://www.nuget.org/packages/OneSignalSDK.DotNet)
