### ISSUE TITLE
[Bug]: ITMS-90482: Invalid Executable - OneSignal contains bitcode. Maui

### ISSUE THREAD

**Issue by andrei25f** [OneSignal/OneSignal-Xamarin-SDK#335]
### What happened?

The problem appeared after updating to Xcode 14.0.1
The App Store rejected the build and sent an email with the following content:

Dear Developer,

We identified one or more issues with a recent delivery for your app, "AppName" 1.0 (1.0.1). Please correct the following issues, then upload again.

ITMS-90482: Invalid Executable - The executable 'AppName.app/Frameworks/OneSignal.framework/OneSignal' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'AppName.app/Frameworks/OneSignalCore.framework/OneSignalCore' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'AppName.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'AppName.app/Frameworks/OneSignalOutcomes.framework/OneSignalOutcomes' contains bitcode.

Best regards,

The App Store Team

### Steps to reproduce?

```Markdown
1. Rebuild Maui project with Visual Studio for Mac 17.3.8 Xcode 14.0.1
2. Run command in terminal: dotnet publish -f:net6.0-ios -c:Release -r ios-arm64
3. Send .ipa file to App Store with Transporter
```

### What did you expect to happen?

AppStore will process the build successfully. No 'bitcode' error

### OneSignal Xamarin SDK version

4.2.0-beta1-maui-only

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by fhboswell** [comment]
@andrei25f We will investigate this further. In the mean time please use Xcode 13 to submit your app to App Store connect. The App Store no longer accepts bitcode submissions from Xcode 14. 
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

**Comment by andrei25f** [comment]
My apologies. It turned out that the problem was not in the OneSignal library. It was necessary to update Visual Studio
