### ISSUE TITLE
OneSignal.Current.ClearOneSignalNotifications() not available

### ISSUE THREAD

**Issue by ndastur** [OneSignal/OneSignal-Xamarin-SDK#34]
As per the documentation
https://documentation.onesignal.com/v3.0/docs/xamarin-sdk#section--clearonesignalnotifications-

I am trying to clear notifications, but the method can not be found. Also can't find anything similar.

**Comment by ndastur** [comment]
Hi Guys. Sorry but any news on this. I need to be able to clear notifications in app and this seems to be the way to do it.

**Comment by falox** [comment]
This is a **regression** and a **breaking change** since the code that was calling `ClearOneSignalNotifications()` is not compiling. 

Can you please fix it or provide a workaround? Thanks

**Comment by ndastur** [comment]
Thanks @falox . Could you point to the source file where code is not compiled? I assume you mean it is commented out or #if def out

**Comment by falox** [comment]
@ndastur My comment is for the OneSignal team. I have the same problem of you. I'm just stressing the fact that the priority of this issue should be increased and a fix provided asap, since all apps that are calling `ClearOneSignalNotifications()`  are not compiling anymore with 3.1.

**Comment by ndastur** [comment]
Yes you are right. Should be quite a simple thing and i' d  make a pull request . However the underlying lib seems to be closed source

**Comment by jkasten2** [comment]
@ndastur This SDK uses compiled binaries but the sources for them are below.
* [OneSignal-iOS-SDK](https://github.com/one-signal/OneSignal-iOS-SDK)
* [OneSignal-Android-SDK](https://github.com/one-signal/OneSignal-Android-SDK)

My time has been split between a number of project but I'll shoot to look into adding and creating a new release within the next few weeks.

**Comment by ndastur** [comment]
Thank you @jkasten2 . It would be really useful

**Comment by falox** [comment]
Hi @jkasten2 , any ETA for this?

**Comment by c0mm4nDer** [comment]
Hi I have solution for xamarin.android see [here](https://gist.github.com/c0mm4nDer/5b6885392e8c3281fbe22cfb40796a83)

Sorry for my poor English.

**Comment by ArgusMagnus** [comment]
Any news on this?

**Comment by ndastur** [comment]
I get the feeling that the Xamarin project is dead ...

**Comment by Im-PJ** [comment]
I contacted their support and this is the reply I got :disappointed: 

> Hello, We plan to update the SDK to address these  issues. Sorry but we don't have an ETA that we provide at this time on these changes. The Android Oreo (API 26) compatibility can be  worked around in the mean time by targeting API level 25. Thanks.

**Comment by jkasten2** [comment]
Apologize for the lack updates, we are scheduling a round of releases. I created issue #62 with more details. Thanks.

**Comment by Nightsd01** [comment]
`ClearAndroidOneSignalNotifications()` has been added to the SDK (#80 )

**Comment by ndastur** [comment]
Ty @Nightsd01 but still doesn't seem to be exposed in the NuGet package. On 3.1.1

**Comment by ndastur** [comment]
Thank you @jkasten2 . Any idea of timeline to next release?

**Comment by jkasten2** [comment]
@ndastur We are aiming to get a release out this week if all goes well

**Comment by ndastur** [comment]
Hey @jkasten2 any news on when this will be released? Thanks

**Comment by jkasten2** [comment]
@ndastur Sorry for the delay, we are making some native SDK changes and are waiting to roll this up into one larger update

**Comment by ndastur** [comment]
Okay @jkasten2 , thanks for the update. Presumably, this will be some weeks off then? NO chance of an interim release with the clear notifications binding in?

**Comment by dimonovdd** [comment]
[ClearOneSignalNotifications](https://documentation.onesignal.com/docs/xamarin-sdk#clearonesignalnotifications)  is described in the documentation about Xamarin SDK, but in fact, there is no such method. 
Why was this issue closed?
