### ISSUE TITLE
[question]: What is the replacement API for IdsAvailable to retrieve the PlayerId in OneSignalSDK.Xamarin?

### ISSUE THREAD

**Issue by matthewrdev** [OneSignal/OneSignal-Xamarin-SDK#347]
### How can we help?

In order to comply with Googles minimum Android v31 targeting requirements, I am migrating a clients app's OneSignal SDK from the Com.OneSignal nuget package to the OneSignalSDK.Xamarin package.

In the previous SDK, there is the following method/callback:

```
OneSignal.Current.IdsAvailable(IdsAvailable);

private void IdsAvailable(string userID, string pushToken) {
     print("UserID:"  + userID);
     print("pushToken:" + pushToken);
}
```

However, in the new SDK, the `OneSignal.Default` instance does not have a matching method nor a `GetPlayerId` function (that I can see).

The [SDK documentation still shows `IdsAvailable`](https://documentation.onesignal.com/v7.0/docs/xamarin-sdk#idsavailable) as a usable method (referring to the old OneSignal.Current methodology) but does not show a replacement.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@matthewrdev Thanks for your question. Depending on your use-cases you may want to use [`OneSignal.Default.PushSubscriptionState.userId`](https://documentation.onesignal.com/docs/xamarin-40-api-reference#push-notifications) and / or [`PushSubscriptionStateChanged`](https://documentation.onesignal.com/docs/xamarin-40-api-reference#state-change-listeners)

**Comment by matthewrdev** [comment]
@jkasten2 Excellent, thanks for the quick answer!

This resolved the issue and I've successfully completed the migration.
