### ISSUE TITLE
[question]: How to create Android Notification Service Extension in xamarin 

### ISSUE THREAD

**Issue by phamhuudat** [OneSignal/OneSignal-Xamarin-SDK#348]
### How can we help?

my project install version onesignal 4.3.0
I want custom Android Notification Service. Please guide me how to edit. thankyou.
Now, I code follow with this link: 
https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension
But not work with me. 
code demo
using static Com.OneSignal.Android.OneSignal;
using Com.OneSignal.Android
 public class NotiServiceExtension : Java.Lang.Object, IOSRemoteNotificationReceivedHandler
{

        public void RemoteNotificationReceived(Context context, OSNotificationReceivedEvent p0)
        {
        }
}

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Acilec** [comment]
Same problem here...
Can't find any working documentation for 4.x.x regarding this.
