### ISSUE TITLE
How do you process push notifications received while the app is in the background?

### ISSUE THREAD

**Issue by Osmosis311** [OneSignal/OneSignal-Xamarin-SDK#351]
### How can we help?

Is there a way to receive an event / handle a push notification that's received when my app is in the background?  I'm using the OneSignal Xamarin SDK, and in the documentation it says to add a notification service extension, and inherit from this class `OSRemoteNotificationReceivedHandler`, but that class isn't found anywhere in the SDK.

Is there a way to do this in the Xamarin SDK?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@Osmosis311 would you be able to share your use case for why you need to receive control when receiving a notification *and* your app isn't in the foreground?

**Comment by Osmosis311** [comment]
Yes. Critical notifications. If the user has their phone completely
silenced, for specific types of critical alerts, I need to be able to run
code when a notification is received and my app isn’t in the foreground
that utilizes MediaManager to play a sound to get the users attention (this
is of course with their consent. The use case here is volunteer emergency
responders. For example, they may be in an office setting and don’t want to
be disturbed except for emergencies happening nearby).

I think I figured it out, though. I registered a (generic) notification
receiver and that seems to be working exactly the way I want.

**Comment by brismithers** [comment]
thanks for the feedback @Osmosis311, I'll pass that along internally as a scenario to account for.  Yes a generic notification receiver would work as well good thought. If you're up for it please post a version of what you did here and I can try to incorporate it as a solution into our docs.

**Comment by Tock3r** [comment]
I need that badly too. @Osmosis311, your solution would be very helpful. :)
In my use case, security guards receive an alarm notification with status messages that they have to acknowledge. If they ignore the notification, the app will periodically remind them with a warning sound.

**Comment by Osmosis311** [comment]
Here's the [code](https://gist.github.com/Osmosis311/0be8cb4b400c97618b39b394024dba10) for the receiver.

Add this to MainActivity.cs in the `OnCreate` function:

`IntentFilter filter = new IntentFilter("com.google.android.c2dm.intent.RECEIVE");                        
  RegisterReceiver(new PushReceiver(), filter);`

**Comment by Tock3r** [comment]
Awesome, it works. Thank you. I had it similar, I only registered the receiver in the launch activity and not in main :D
