### ISSUE TITLE
Error Getting Google Registration ID

### ISSUE THREAD

**Issue by William-H-M** [OneSignal/OneSignal-Xamarin-SDK#36]
Hi, I'm having the following problem with a Xamarin.Forms PCL, this happens with the given sample on this repo

The error shows the following (Paste it for Web searcher Indexers)

```
Error Getting Google Registration ID INVALID_PARAMETERS 
at
 com.google.android.gms.gcm.GoogleCloudMessaging.register(UnknowSource)
at
com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:151)
at
java.lang.Thread.run(Thread.jave:841)
```

This usually happen after the app is initialized, then put app on background, a message arrives and open it through the notifications then the error happens, after repeat the same.

What I think It could be is that the same activity or task is running again
Does anyone else have this problem or have hit this wall?

In advance thanks for help given!

EDIT; looks like it's was a problem with duplcating task

**Comment by lafritay** [comment]
@William-H-M I'm hitting this same error.  Care to elaborate on how you fixed it?
