### ISSUE TITLE
[question]: Xamarin.IOS OneSignalNotificationServiceExtension Linker Settings are different error

### ISSUE THREAD

**Issue by turgaygncr** [OneSignal/OneSignal-Xamarin-SDK#376]
### How can we help?

Hi,

I'm using VS4Mac 2022, and integrated my xamarin project with Onesignal.SDK via v.9.0 documantation.
I complated all set up but I'm getting error wgile archiving ios project.

The error is:
Native code sharing has been disabled for the extension 'OneSignalNotificationServiceExtension' because the managed linker settings are different between the container app (SDKOnly) and the extension (None).

There is no Arm64 option on extention project build settings. I changed several options but got errors always.

Could you help please ?

My main Xamarin.IOS project build setting:
![Ekran Resmi 2023-04-07 09 23 17](https://user-images.githubusercontent.com/5506941/230553622-758facd6-a6a3-4b93-9501-ac656240566e.png)

That is also my OneSignalNotificationServiceExtension project build setting:
![Ekran Resmi 2023-04-07 09 23 51](https://user-images.githubusercontent.com/5506941/230553683-a1118b63-62d6-4ce3-82fc-bea3f8594394.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robfrancis** [comment]
I think you are looking in the wrong place on your OneSignalNotificationServiceExtension project.
Try changing the values below to 'AppStore' & 'iPhone'. I'm assuming the 'Linker Behaviour' will need to match.

![Debug_IphoneSim](https://user-images.githubusercontent.com/5869183/231019126-bc7233d9-14af-4702-8ec6-dca61afe56cc.jpg)

**Comment by emawby** [comment]
@turgaygncr Hello did the above suggestion resolve your issue?
