### ISSUE TITLE
[question]: Does this work with .Net IOS and .Net Android (.Net 6/7) or is there plans/another repo for that?

### ISSUE THREAD

**Issue by IainS1986** [OneSignal/OneSignal-Xamarin-SDK#379]
### How can we help?

As Xamarin is end of life, is there, or are there, plans for a .Net 6/7+ support we can switch over too?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello we have a separate [repository/SDK](https://github.com/OneSignal/OneSignal-DotNet-SDK) for .Net!
