### ISSUE TITLE
Onesignal.Current.StartInit

### ISSUE THREAD

**Issue by jzeferino** [OneSignal/OneSignal-Xamarin-SDK#38]
I'm updating and old project (1 year old) that uses `OneSignal` previous to the Nuget package were available.

One of the big things that changed is that in the new version the `StartInit` must receive the `appid`. 

In my manifest I still have the `appid` configured.

```
<meta-data android:name="onesignal_app_id" android:value="app_id" />
<meta-data android:name="onesignal_google_project_number" android:value="str:number" />
```
Any reason for the `StartInit` method only have one overload that need to receive the `app_id`.
In my particular case, does it need to be removed from manifest @jkasten2 ?

**Comment by jkasten2** [comment]
@jzeferino If you include it in the `AndroidManifest.xml` as you have above it will use this `app_id` instead of the one from code.

The Google Project number / Sender ID is used from the Android configuration setting shown on the OneSignal dashboard now so make sure to fill this in.

Thanks.

**Comment by jzeferino** [comment]
For new projects, where can I get the `onesignal_google_project_number` since its unique per `packagename`?

**Comment by jzeferino** [comment]
Thanks for the response @jkasten2.
For new projects, where can I get the `onesignal_google_project_number` since its unique per `packagename`?

**Comment by jkasten2** [comment]
@jzeferino  The `onesignal_google_project_number` is `AndroidManifest.xml` entry is deprecated. The value on the OneSignal dashboard currently overrides this. `onesignal_google_project_number` is only use for backwards compatibility.

**Comment by jzeferino** [comment]
@jkasten2 ok, it makes sense now. I'm working on a old project that used to use the `onesignal_google_project_number`. Since I've updated to the new nuget version, I can safely remove that from `AndroidManifest.xml,` correct?

**Comment by jkasten2** [comment]
@jzeferino Correct, however if you setup the Android platform on OneSignal before Oct. 2016 you will need to add the Google Project number to the App Setting page before doing so.

**Comment by jzeferino** [comment]
@jkasten2 can you tell me in the page were is this setting placed?

**Comment by jkasten2** [comment]
@jzeferino Step 3 of this guide below shows the location of this field.
https://documentation.onesignal.com/docs/generate-a-google-server-api-key#section-3-configure-your-onesignal-app-s-android-platform-settings

**Comment by jzeferino** [comment]
@jkasten2 thanks a lot. One last clarification. In this project that I'm talking, the android application has two flavors that only change the `packagename` and `app_id` but the `onesignal_google_project_number` remains the same for both. Whats the implications of it?

Example for flavor 1 I got:
```
packagename: com.myapp
app_id: 123456789
onesignal_google_project_number: 123

```
Example for flavor 2:
```

packagename: com.myapp.dev
app_id: 987654321
onesignal_google_project_number: 123
```

**Comment by jkasten2** [comment]
@jzeferino You can use the same Google project number for both OneSignal app ids without any issues. For totally different apps it is recommend to create a new FCM project so it could be transferred to another user in the future. However not required.

**Comment by jzeferino** [comment]
@jkasten2 I appreciate the support! 👍
