### ISSUE TITLE
MT4118 Error in iOS Project Regarding System.Net.Http

### ISSUE THREAD

**Issue by landrzz** [OneSignal/OneSignal-Xamarin-SDK#40]
MT4118: Cannot register two managed types ('*' and '*') with the same native name ('*').
Tested on Xamarin 2.3.4+

This can be easily reproduced by doing File->New 
Loading in the OneSignal Nugets (3.0.0 or 3.0.1)
Adding the bits of code from the Xamarin OneSignal SDK Docs (Forms on Singleview. Same error)
Ensure all profiles, certs, and settings are correct in Info.plist and Options menu, etc.

The following error happens every time...

![screen shot 2017-05-17 at 10 22 34 am](https://cloud.githubusercontent.com/assets/7349328/26158795/d5a6f28c-3aea-11e7-85fd-49d9be0fd7d8.png)

**Comment by jzeferino** [comment]
@landrzz are you using Xamarin Studio or Visual Studio for Mac?

**Comment by landrzz** [comment]
This turned out to be a bug on the beta channel of Visual Studio for Mac. It was fixed within a week or so. I apologize for forgetting to close this issue.
