### ISSUE TITLE
OSNotificationPayload Documentation

### ISSUE THREAD

**Issue by duraes** [OneSignal/OneSignal-Xamarin-SDK#44]
Hi

Im using OneSignal Xamarin, version 3.0.1.0.

In [This documentation article](https://documentation.onesignal.com/v3.0/docs/xamarin-sdk#section--notificationopened-) about user input on the notifications, the reference docs for the property additionalData, shows type as Dictionary<string, string>, but in the 3.0.1.0 libs we have Dictionary<string, object>.

The raw Payload property stated in the [docs](https://documentation.onesignal.com/docs/xamarin-sdk#section--osnotificationpayload-), does not exist at all.

**Comment by Nightsd01** [comment]
@duraes Thank you for reporting this, our docs have been updated and the `additionalData` object is correctly documented as being `Dictionary<string, object>`.
