### ISSUE TITLE
Scheduling restart of crashed service com.onesignal.SyncService

### ISSUE THREAD

**Issue by thiagof0701** [OneSignal/OneSignal-Xamarin-SDK#46]
Service crashes when i remove app from background and then it stops receiving notification.
It only receives notification when app is running.

If i pressed home and killed the app after onesignal had sent all requests service restarted properly. It crashed when i removed the app from background immediately.

It was fixed in the version 3.4.4 and I am waiting the pull request #43

**Comment by ndastur** [comment]
Hi Guys. Any news on a NuGet update. We are still on 3.0.1. Thanks

**Comment by jkasten2** [comment]
I believe this issue should be fix in the 3.1.0-alpha release if you want to give it a try to confirm.
https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases

**Comment by jkasten2** [comment]
This is now fixed in the latest [OneSignal Xamarin 3.1.0 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.1.0)!
