### ISSUE TITLE
No Push Notification received when app closed

### ISSUE THREAD

**Issue by corgalore** [OneSignal/OneSignal-Xamarin-SDK#48]
I have a Xamarin Forms PCL-based project that will not receive push notifications on Android when the app is closed. It works correctly when the app is open or running in the background. The OneSignal dashboard reports the message as 'Delivered'. I've been testing with a wired Galaxy over a debug session with VS 2017.

- Galaxy S7 Edge
- Xamarin.Forms NuGet v2.3.4.247
- Com.OneSignal NuGet v3.0.1

I have followed the SDK setup guide to add the init method in the Forms App constructor:

```
public App()
{
            InitializeComponent();

            OneSignal.Current.StartInit("9999-9999-9999-9999-9999")
                .InFocusDisplaying(Com.OneSignal.Abstractions.OSInFocusDisplayOption.Notification)
                .EndInit();
}
```

I have also tried placing this directly in the Android project MainActivity.cs -> OnCreate method.

The AndroidManifest.xml looks like so:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.TEST.App" android:versionCode="1" android:versionName="1.0" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="15" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
  <permission android:name="com.TEST.App.permission.C2D_MESSAGE" android:protectionLevel="signature" />
  <uses-permission android:name="com.TEST.App.permission.C2D_MESSAGE" />
	<application android:label="@string/app_name">
    <receiver android:name="com.onesignal.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.TEST.App" />
      </intent-filter>
    </receiver>
  </application>
</manifest>
```

Am I just missing something?

**Comment by gdeglin** [comment]
Android applications that have been force stopped in the settings or by the launcher can not receive notifications. Here's our documentation on this and other reasons this can happen: https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

Closing this for now, but feel free to follow up if this doesn't solve your problem.

**Comment by corgalore** [comment]
Hmm, you're right. I disconnected the debugger, restarted the device, opened and closed the app and now it works when the app is closed. Thanks!
