### ISSUE TITLE
Handle Action button direct reply

### ISSUE THREAD

**Issue by softsan** [OneSignal/OneSignal-Xamarin-SDK#50]
Hi,

Went through this [code ](https://documentation.onesignal.com/docs/xamarin-sdk#section--notificationopened-) for handling Action button in OneSignal push notification.

I need to further know whether it is possible to have a Direct reply when a notification comes in. For example. The app is not running and notification arrived, so user should be able to "Reply" back without opening the App (just like Skype). 

Is it possible using Xamarin(android and iOS) ?

**Comment by jkasten2** [comment]
@softsan The in-line replying in the notification you are describing is currently not a feature in the native [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) and [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK) SDKs used by this SDK. Marking this as feature request where we can circle back once those SDKs have implemented this feature.

**Comment by rgomezp** [comment]
Closing. Issue still internally under consideration
--

**Comment by softsan** [comment]
@rgomezp  hi is there any update on this?

**Comment by rgomezp** [comment]
Howdy @softsan ,
This is not something I would expect in the near future. We do hope to build this eventually however. Enjoy
