### ISSUE TITLE
Support for Windows 10(UWP)

### ISSUE THREAD

**Issue by amoraitis** [OneSignal/OneSignal-Xamarin-SDK#53]
Support for setting up notifications on uwp projext(in xamarin forms) would be helpful.

**Comment by jkasten2** [comment]
Thanks, we will consider supporting this

**Comment by ArgusMagnus** [comment]
Any news on this?

**Comment by ArgusMagnus** [comment]
With all the Windows 10 devices out there (I know mobile is dead, but PCs, tablets and XBox are in widespread use) this would be an appreciated extension of your service.

**Comment by jkasten2** [comment]
@amoraitis @ArgusMagnus We currently do not have a native SDK for this yet however OneSignal's dashboard / backend does support the WNS push protocol.
We have overview you can follow to register the device with OneSignal start sending pushes
https://documentation.onesignal.com/docs/windows-app-sdk-setup

**Comment by ArgusMagnus** [comment]
Are you planning to release a native UWP SDK at some point in the future?

**Comment by AmitKKhanchandani** [comment]
Hi, is there any update/progress in this?

**Comment by EmilAlipiev** [comment]
When I go to portal configuration shows UWP as in the image. Does it mean that we can use UWP also now? Documentation still stays WP8.1
Can somebody shed some lights here please?

![image](https://user-images.githubusercontent.com/10422347/45621578-2212b900-ba81-11e8-9403-c7ac4656ce46.png)

**Comment by jkasten2** [comment]
@EmilAlipiev OneSignal does not have an SDK for UWP apps. However since OneSignal's backend and dashboard supports the WNS push protocol you can send push notifications from OneSignal if you add your own code to register the device.
See this documentation page for details.
https://documentation.onesignal.com/docs/windows-app-sdk-setup

The link is out of date on that page, we will updated it to reflect the above.

**Comment by EmilAlipiev** [comment]
@jkasten2  thats what i though also. i am looking forward for the documentation update. thanks

**Comment by rgomezp** [comment]
Closing. Issue still internally under consideration
--
