### ISSUE TITLE
Push Notification does not appear on Android Oreo (using Target Framework 26)

### ISSUE THREAD

**Issue by alexshikov** [OneSignal/OneSignal-Xamarin-SDK#57]
As soon as notification arrives an error happens:
```
E/BroadcastReceiver(26895): BroadcastReceiver trying to return result during a non-ordered broadcast
E/BroadcastReceiver(26895): java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
```

The same error described here https://stackoverflow.com/questions/23835970/broadcastreceiver-trying-to-return-result-during-a-non-ordered-broadcast-packa

Switching **Target Framework** back to 25 get the app work again.

**Comment by jkasten2** [comment]
Merging with issue #54 as this is same root problem. Also 3.1.0-alpha has been release to Nuget so you can start testing a fix we have
