### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by geedsen** [OneSignal/OneSignal-Xamarin-SDK#58]
Just cloned the SDK and did a build in VS2017. I get this error:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.ObjCBinding.CSharp.targets (58,3) MSB4044: The "BTouch" task was not given a value for the required parameter "BTouchToolPath".

Google does not help me here, suggestions?

**Comment by geedsen** [comment]
Some more info: I just noticed that the Com.OneSignal.Abstractions reference in the Com.OneSignal.iOS project shows this 'error' icon (yellow triangle). So I removed the reference and tried to add it again. It then tells me that the targets of the portable class library are incompatible with the iOS project. Checking the targets on the pcl project, shows that Xamarin.iOS (Classic) is enabled.

**Comment by jkasten2** [comment]
@geedsen Can you try updating to the latest master? We just switched both the `Com.OneSignal.Abstractions` and `Com.OneSignal` projects to .NET Standard. Make sure your on the latest Visual Studio and Xcode if you are still having issues. Please provide a screenshot if you are still suck on any issues. Thanks!

**Comment by Nightsd01** [comment]
Closing due to no response
