### ISSUE TITLE
Can this be used in server?

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Xamarin-SDK#59]
If not will there be official SDK in C# for server?

**Comment by jkasten2** [comment]
@Thaina This project is a client side SDK for iOS and Android apps. We currently do not have any official server side libraries. There is a community developed one below if you haven't checked out already.
https://github.com/mundipagg/OneSignal-CSharp-SDK
I haven't used it so can't say if it has any limitations or issues.

Our REST API is easy to use and we provide C# examples so I recommend checking our documentation below.
https://documentation.onesignal.com/reference

If you have any issues with the REST API I recommend contacting OneSignal support from the chat bubble in the bottom right while signed into the OneSignal dashboard.
