### ISSUE TITLE
Release Schedule - March 2018

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#62]
We apologize for the absence of updates to this SDK. I have reviewed the current issues and we are going to prioritize issue #56 *(.NET Standard)* and issue #54 *(Android API level 26 support)* since these are show stoppers for a number of developers. We are going to shoot for a release containing these two fixes by the end of March. After this release we will follow up shortly with another release tackling a few of the other issues such as #34 *(Missing ClearOneSignalNotifications)*.

Going forward we will be providing more frequent updates as we do with our other OneSignal SDKs. We understand that active updates and maintainers is a large factor in choosing and continuing to use a library in your project.

**Comment by ArgusMagnus** [comment]
Thats very good to hear!

Will you accept contributions? There are a number of things which are untypical for .NET libraries with which I'd love to help (e.g. provide proper async/awaitable methods for all the methods which take a callback as parameter (like GetTags)) .

**Comment by jkasten2** [comment]
@ArgusMagnus yes, pull requests are welcome!

Good point on GetTags, feel that async would be best for this as well. However we will still want delegates for something like the notification open event.

**Comment by ArgusMagnus** [comment]
sure, or maybe events would be even nicer, I dont think it matters much though

**Comment by ArgusMagnus** [comment]
What is the plan regarding #49? Not being able to implement a NotificationExtenderService is a show stopper for us (required for https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding).

**Comment by xalikoutis** [comment]
Also  #49 very important for us almost urgent

**Comment by jkasten2** [comment]
@ArgusMagnus @xalikoutis Thanks for the feedback. Issue #49 is reporting that `HandleNotificationOpened` is not firing on cold start which is a bug. This along with #34 are smaller bugs which we can release shortly after our end of March update.

For adding that `NotificationExtenderService` support, it seems this might be the only thing required.
https://github.com/thefex/OneSignal-Xamarin-SDK/commit/0f42e02cbf1d26c4c79d3695af35e38e97e9cfe1#diff-885828d64f5568a1ca28dc108f962ad5R3
@thefex Did this single change work in your testing? If not we can dig in more after addressing the other issues above

**Comment by stringo** [comment]
+1 @xalikoutis, #49 is also urgent, hope we can see this fix in a short period of time after the release at the end of this month.

@jkasten2, thank you so much for supporting this project. OneSignal is awesome and this is by far the most simple yet powerful SDK for Push Notifcations in the Xamarin.Forms world.

**Comment by thefex** [comment]
@jkasten2 yup, working in production app, feel free to ask if something is unclear

**Comment by AshIceLoky** [comment]
Very nice .... I wait this with impatience ........

**Comment by jkasten2** [comment]
Just published a 3.1.0-alpha to Nuget as a pre-release. This first alpha just includes an updated Android native library so you can start testing targeting API Level 26+ on Android 8+. (Addressing issue #54)
https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases
We will follow up with anther alpha update soon as we address #56 (.NET Standard)

**Comment by jkasten2** [comment]
We just published a [3.1.0 beta release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.1.0-beta) that now supports .NET Standard projects. Please try it out and let us know if there are any issues.

**Comment by xalikoutis** [comment]
Hi after updated to 3.1.0 beta all the user in onesignal under SUBSCRIBED says (Missing Google Play Services Library

They dont get notifications

**Comment by xalikoutis** [comment]
I added manually Xamarin.GooglePLayServices.Gcm and it is working now?

**Comment by jkasten2** [comment]
@xalikoutis Visual Studio should have added the following automatically when adding OneSignal.
![image](https://user-images.githubusercontent.com/645861/38052489-3ce52138-3286-11e8-8f8f-8cf6c51a8602.png)

Did you get any errors or warnings when adding OneSignal at the time?

**Comment by xalikoutis** [comment]
just updated the nuget package, i didnt get any errors

**Comment by jkasten2** [comment]
[OneSignal Xamarin 3.1.0](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.1.0) is now released!

**Comment by xalikoutis** [comment]
Hi is #49 is working on Xamarin Forms Android? Whats the status of the issue?

**Comment by LuisDeHaro** [comment]
Hi, I'm looking forward to see the #49 implemented as well. Thanks in advance!

**Comment by jkasten2** [comment]
@xalikoutis @LuisDeHaro In #49 @Nightsd01 noted that the issue was not longer reproducible. Please follow up in #49 if you can reproduce the problem still. Provide code your using and Android versions you are testing on as well as any logs you can provide.

#34 is the last issue mentioned here that isn't in a release but it is in master and it will be included in the next release. Closing this ticket as everything has been completed for the March 2018 release this ticket was created for.

For any new problems please create new github ticket instead of replying here.

**Comment by Doughouzlight** [comment]
Hi @jkasten2  what about the  NotificationExtenderService class can you show us some example of it?

**Comment by esaavedra89** [comment]
Hi everyone, I'am using VS 15.6.2 and my project is a .Net Standard, when I was installing OneSignal nuget I was getting the error about the project Android, and I was needing to install Googleplayservices.base but I was getting errors and erros. So my solution was:
1-Try to unistall all the Googleplayservices.base (If you have someone)
2-Clear all the nugets cache.
3-Close VS.
4-In the project's folders, clear the contens of the folders "bin" and "Obj".
5-Start VS and reinstall the OneSignal Nuget. I'm using the V 3.0.1 

That is my solution.

I hope that can help you.

**Comment by jkasten2** [comment]
@Doughouzlight We don't have an example for C# yet, however it is very similar to the Java example here:
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

@esaavedra89 Could you open a new ticket for the error you are seeing? In new Issue please include the full error you were getting so we can suggest a fix.

Locking this thread, please check the existing open issues if they apply. Open new issue after searching if none apply.
