### ISSUE TITLE
Receiving notifications when app is not running on Android?

### ISSUE THREAD

**Issue by MihaMarkic** [OneSignal/OneSignal-Xamarin-SDK#63]
What blackmagick do I have to do to receive notifications on Android when app is not running?
Is this something I have to enable somewhere?
When app is running everything is cozy.

**Comment by AndreiMisiukevich** [comment]
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        <receiver android:name="com.onesignal.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="YOUR_APP_PACKAGE_ID" />
            </intent-filter>
        </receiver>

add this into <application></application> tag

And test it in release mode

**Comment by MihaMarkic** [comment]
I just saw #48 . That's was how I  tested and obviously it wouldn't work.
So how am I supposed to test this scenario then? Creating a  release version, restart the device and then send notification?

**Comment by AndreiMisiukevich** [comment]
@MihaMarkic it was representation bug on github
see my comment above)

**Comment by MihaMarkic** [comment]
@AndreiMisiukevich "add this into tag" and no hyperlink is a bit cryptic :)

**Comment by AndreiMisiukevich** [comment]
@MihaMarkic magic)

http://prntscr.com/im7mvb

**Comment by AndreiMisiukevich** [comment]
[111.txt](https://github.com/OneSignal/OneSignal-Xamarin-SDK/files/1777303/111.txt)

**Comment by MihaMarkic** [comment]
Yep, I already have that. The core problem was that I was force stopping the app to test it. And that way it doesn't work.
Do you know a friendly way to test it? Or is the only option to restart device each time you want to test it?

**Comment by MihaMarkic** [comment]
I'll close this and create a new issue.
