### ISSUE TITLE
How to test cold start Android app from Notification?

### ISSUE THREAD

**Issue by MihaMarkic** [OneSignal/OneSignal-Xamarin-SDK#64]
Since force stop app won't work, how does one test cold start from notification?
Is the only way to restart the device each time?

**Comment by jkasten2** [comment]
@MihaMarkic If you swipe away the app from the recent apps list this will be a normal close on Android. There are a fews devices that are an exception to this rule such as some Xiaomi devices.

If you don't see a notification and you see the following in your logcat then this this normally indicates the app was force closed.
`W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.onesignal.example (has extras) }`

There are some additional details the OneSignal documentation on the force closed state and other devices below.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by MihaMarkic** [comment]
Oh, right. I was stopping the debugger and application was of course force stopped.
I just assumed that force close is swiping it away as well, but later found out that in fact wasn't.

Thanks
