### ISSUE TITLE
White square in notification bar instead of app icon on Android 5

### ISSUE THREAD

**Issue by AndreiMisiukevich** [OneSignal/OneSignal-Xamarin-SDK#65]
Hi

https://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop

https://stackoverflow.com/questions/30795431/icon-not-displaying-in-notification-white-square-shown-instead

The same behavior we have, but how can I fix it, if I use your plugin?)

Thanks!

**Comment by AndreiMisiukevich** [comment]
Hm, several topics said me, that I would use white icons with transparent background for Android 5 and above.. Ok, how can I set default push icon for Android?... And Why Is it working for me on Android 6+.. I can't undestand

**Comment by jkasten2** [comment]
@AndreiMisiukevich I recommend using the [Android Asset Studio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) to generate your small notification icon. If it is a white square there it will look this way on the device.

You are correct about the transparently, you will need to edit your icon to be transparent in the shape you would like it to show before uploading it though.

Xiaomi or Huawei devices have custom UIs that don't always follow this rule for Android small icons. Let us know the device model if it isn't one of these devices.

For those looking for details on the file name and other icons see the link below.
https://documentation.onesignal.com/docs/customize-notification-icons#section-1-generate-icons

**Comment by AndreiMisiukevich** [comment]
@jkasten2 thanks for quick response, colleague!)
