### ISSUE TITLE
iOS: get whether user allowed push notifications or not

### ISSUE THREAD

**Issue by MihaMarkic** [OneSignal/OneSignal-Xamarin-SDK#66]
Is there a way to wait for user to allow push notifications or deny?
Right now the dialog seems async after EndInti();

**Comment by jkasten2** [comment]
@MihaMarkic There currently isn't a callback / async method for when permission prompt is answered. However you can use [IdsAvailable ](https://documentation.onesignal.com/docs/xamarin-sdk#section--idsavailable-) to know when device is registered after they answer the prompt. `userID` will be non-null when the device registers with OneSignal and `pushToken` will be non-null if the devices successfully registered with APNs and your app has notification permissions. 

The OneSignal native iOS SDK does have a callback for the permission prompt response itself we will hooking up in the future to the Xamarin SDK.

**Comment by MihaMarkic** [comment]
Please, add that. IdsAvailable is not the same as there might be other causes, I guess (i.e. no internet connected). When exactly do I get IdsAvailable callback?

**Comment by rgomezp** [comment]
Closing. Issue still internally under consideration
