### ISSUE TITLE
How to resolve when we not allowed notification.

### ISSUE THREAD

**Issue by carl-neng** [OneSignal/OneSignal-Xamarin-SDK#68]
When I click not allow notification first time like picture ::

![c25380ccc59cff2f24cf01ecf5d57253954b394017b147abd5 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/22851711/37320576-f1daf496-26a6-11e8-81b2-c86388c64398.jpg)

And on onesignal app no see SUBSCRIBED like picture 

![image](https://user-images.githubusercontent.com/22851711/37320649-3c3d38b4-26a7-11e8-8421-d0df40d86526.png)

So how can I set it to SUBSCRIBED again. I want to see it subscribe status. I have check xamarin sdk don't have method for check it. So I hope help me... thank you advance.

@gdeglin I hope so that you can help me.

**Comment by jkasten2** [comment]
@carl-neng If the user presses "Don't Allow" on the native iOS notification permission prompt, the user will need to go to Settings > Notifications > [Your app] to enable them. iOS does not have a way to show this prompt again.

**Comment by carl-neng** [comment]
@jkasten2  Yes thank you so much.
