### ISSUE TITLE
Group notifications.

### ISSUE THREAD

**Issue by ugnivs** [OneSignal/OneSignal-Xamarin-SDK#75]
Can i somehow manage notifications grouping on a client side ? I'm using sdk version 3.1.0 and have overriden notificationextender service. All works fine when i recieve single notification, it goes through my service as expected. but when i recieve the secon one with the same group, my service is ignored and i've the notification with ring bell instead of my icons. Can i make grouping with possibility to uncover it and open the concrete notification of the group?

**Comment by jkasten2** [comment]
@ugnivs Can you provide a few more detail?
1. What device models and versions of Android are you testing on?
2. Can you add logging to your `NotificationExtenderService` to see if it firing at all on the 2nd notification?
3. Can you share your `NotificationExtenderService` code?
4. Can you share the dashboard options or the JSON payload you are sending if you are using the REST API?

**Comment by ugnivs** [comment]
@jkasten2 
`public class NotificationExtender : NotificationExtenderService, NotificationCompat.IExtender
    {
        private OSNotificationReceivedResult _result;
        protected override void OnHandleIntent(Intent intent)
        {
        }

        protected override bool OnNotificationProcessing(OSNotificationReceivedResult p0)
        {
            _result = p0;
            var overrideSettings = new OverrideSettings { Extender = this };
            DisplayNotification(overrideSettings);
            return true;
        }

        public NotificationCompat.Builder Extend(NotificationCompat.Builder builder)
        {
            builder.SetSmallIcon(Resource.Drawable.ic_notification)
                .SetContentTitle(_result.Payload.Title)
                .SetContentText(_result.Payload.Body);
            return builder;
        }
    }`
here is the code of notification extender service. For my test OnNotificationProcessing is fired three times for three notifications. Two of them are from one group. And here is the result:
![20180328_125207](https://user-images.githubusercontent.com/17256340/38022043-2703253a-3287-11e8-98de-aa8785cd9b1a.png)
Why is it so?

**Comment by jkasten2** [comment]
When 2 notifications are received with the same group a summary notification is created which is actually a different notification. The summary notification will always use the default small icon. You will need to follow this guide to add this so your grouped notifications looks like your other non-grouped notifications.
https://documentation.onesignal.com/docs/customize-notification-icons

The NotificationExtenderService does not have the ability to effect the summary notification.

**Comment by ugnivs** [comment]
@jkasten2 Will the NotificationExtenderService ever have the ability to effect the summary notification? Thank you for answers

**Comment by jkasten2** [comment]
It is something we my add support for in the future, it would have to be added to the [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) so feel free to open up an issue to request this feature if it is important to you.

Setting a default notification icon noted above should however get what you need though without using the `NotificationExtenderService` at all. Did it not work for you? Or do you need different icons for different groups?

**Comment by ugnivs** [comment]
@jkasten2  Ideally, i need to have a possibility to uncover collapsed notifications and open any concrete notification, but it seems that it's not possible. With icons everything is fine

**Comment by jkasten2** [comment]
@ugnivs This is what Android 7+ does, the user can expand the summary notification and can fully see and interact with each one.
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#bundle
