### ISSUE TITLE
Missing debugging symbols on NuGet

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#79]
Since switching the `.nuspec` to .NET Standard the debugging symbols were dropped in the 3.1.1 release. The follow error occurs in Visual Studio:
> Failed to read ' Droid\obj\Release\android\assets\OneSignal.Android.Binding.dll' with debugging symbols. Retrying to load it without it.

**Comment by jkasten2** [comment]
@EmilAlipiev I [manually downloaded](https://www.nuget.org/api/v2/package/Com.OneSignal/3.1.1) our [3.1.1 nuget package](https://www.nuget.org/packages/Com.OneSignal/3.1.1) and found it contains the following debug symbol files.  
```
OneSignal.iOS.Binding.pdb
Com.OneSignal.pdb
OneSignal.Android.Binding.pdb
Com.OneSignal.pdb
Com.OneSignal.Abstractions.pdb
```

Could you provide a step by step of how you got this error?

**Comment by EmilAlipiev** [comment]
well, i didnt do anything specific. just installed this version and rebuilt in release and finally tried to deploy into my android phone. it returned this error. you already confirmt that there are pdb symbols. are we supposed to have those if it is published in release mode to Nuget?

**Comment by Nightsd01** [comment]
Resolved in 3.2.0

**Comment by EmilAlipiev** [comment]
> Failed to read 'myApp.Droid\obj\Release\android\assets\OneSignal.Android.Binding.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.


it doesnt seem to be resolved in 3.2.0. still this message is appearing

**Comment by vkurilenko** [comment]
in version 3.2.0 same effect

**Comment by EmilAlipiev** [comment]
this is still the case and it causes packing to fail when using AOT

> 
> obj\Release\android\assets\OneSignal.Android.Binding.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
>    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
>    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
>    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)

**Comment by EmilAlipiev** [comment]
3.2.2 still same error, in the logs it appears. Such a pity, such nice library, i have to remove from my projects. this is just not professional at all. You can just fix such simple warning with in a few minutes but we have been waiting for a year almost.

`\obj\Release\90\linksrc\OneSignal.Android.Binding.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.`

**Comment by EmilAlipiev** [comment]
I recognized that Onesignal library causes building and archiving take longer because of this warning. I installed 3.3.0 pre version and problem persists
