### ISSUE TITLE
v3.1.0/3.1.1: No longer receive notifications on Android 7.0

### ISSUE THREAD

**Issue by ArgusMagnus** [OneSignal/OneSignal-Xamarin-SDK#83]
After upgrading to the new nuget packages I no longer receive notifications on my android test device (which was working fine with v3.0.1)

I resolved the issue by manually adding a reference to Xamarin.GooglePLayServices.Gcm and Xamarin.Android.Support.Compat as suggested by @xalikoutis in #62. It seems like nuget is unable to automatically select the correct package version due to some conflicting constraints.

Im using OneSignal in a Xamarin.Forms project which might be part of the reason why this did not happen for other users.

**Comment by jkasten2** [comment]
@ArgusMagnus Did you get an error when you added OneSignal to your Droid project? If so can you share this?

I believe this is the same issue as #81 so going to close this issue in favor of this one

**Comment by ArgusMagnus** [comment]
I should have been clearer, the project is compiled with v8.1, just the test phone runs v7. I did not get any errors when updating the nuget package. (I'll post some more details once Im at my desk)
