### ISSUE TITLE
Android - HandleNotificationOpened not firing when cold started from a notification

### ISSUE THREAD

**Issue by LuisDeHaro** [OneSignal/OneSignal-Xamarin-SDK#86]
Regarding #49 

I can still see the issue in the following environment:

Xamarin.Forms version: 2.3.4.247
OneSignal version: 3.1.1
Project Target Version: Android 8.1
Device: Samsung Galaxy S6 - Android 5.0.0 - API 21

This is the code I'm using:

App.xaml.cs:

```
public App()
{
	InitializeComponent();

	OneSignal.Current.StartInit(Settings.OneSignalAppId)
	 .HandleNotificationOpened(HandleNotificationOpened)
	 .EndInit();
}

async void HandleNotificationOpened(OSNotificationOpenedResult result)
{
	// the alert is not working on COLD start	
	await App.Current.MainPage.DisplayAlert("Header", "Body", "OK");
}

```

It is the same behavior, the HandleNotificationOpened void is reached only if the App active or in the background. Not when it's cold started.

What Android/XF versions did you test that didn't show the issue?

**Comment by ArgusMagnus** [comment]
I believe you are mislead by the way you try to verify if the method is called.
Im using the exact same Environment and it works, but trying to access/modify UI Elements when the app is cold started will Crash your app, probably because Xamarin.Forms is not ready by the time the callback is called.
Try the following:

	public App()
	{
		InitializeComponent();

		OneSignal.Current.StartInit(Settings.OneSignalAppId)
		 .HandleNotificationOpened(HandleNotificationOpened)
		 .EndInit();
	}

	static string _myText = "Normal Start";

	static async void HandleNotificationOpened(OSNotificationOpenedResult result)
	{
		_myText = "Cold Start";
	}

	protected override void OnStart()
	{
		await App.Current.MainPage.DisplayAlert("Header", _myText, "OK");
	}

**Comment by ketanparekh** [comment]
OneSignal version: 3.2.0

in Above answer It always display "Normal Start" as alert.
