### ISSUE TITLE
App Android in background restart after click notification

### ISSUE THREAD

**Issue by rudacs** [OneSignal/OneSignal-Xamarin-SDK#87]
Hello,

I am having a problem with android, when the app is in the background and I click on the notification the app is restarted, recreate the Splash.
And then the application starts from scratch.

**Comment by ArgusMagnus** [comment]
Im not sure, but isn't this standard behavior in Xamarin Forms?

**Comment by rgomezp** [comment]
Hello,
Are you using deep-linking. If so, does that work or no?

**Comment by rgomezp** [comment]
Closing due to no response
