### ISSUE TITLE
Add pdb file into com.onesignal.3.1.1.nupkg

### ISSUE THREAD

**Issue by vkurilenko** [OneSignal/OneSignal-Xamarin-SDK#92]
com.onesignal.3.1.1.nupkg does not contain *.pdb  for NetStandart variant

**Comment by Nightsd01** [comment]
Hi @vkurilenko, we see that the nupkg clearly doesn’t have the pdb files, thank you for bringing this to our attention. We will change the package settings to make sure it’s included when we build the next release.

**Comment by Nightsd01** [comment]
@vkurilenko This should now be resolved in 3.2.0
