### ISSUE TITLE
OTHER Apns 3000 Error

### ISSUE THREAD

**Issue by salmahosni5771** [OneSignal/OneSignal-Xamarin-SDK#94]
**Description:**
I got this "error other Apns 3000 Error" returned from APNS asking for enabling the Push notification on capabilities however i double checked and found it's ticked

**Environment**

**Steps to Reproduce Issue:**
--tried to re produce the certificate using the one signal provisioning tool
-- Double checked the Push notification is enabled in the whole Project
-- Added the asp-Environment to the Entitlement.plist

**Comment by Nightsd01** [comment]
Hi, this would be an issue with the certificate/bundle ID, not an issue with the OneSignal Xamarin SDK.

Please contact OneSignal's support and we'd be happy to help there, we would want to get some more information from you (ie. your App ID). Go to https://www.onesignal.com and click the ? button

**Comment by salmahosni5771** [comment]
Hi, i believe there's no issue with the bundle ID / Certificate as when starting the app on iphone device  i got the pop up for allowing the notification.
