### ISSUE TITLE
Missing new GDPR features in 3.1.1

### ISSUE THREAD

**Issue by zonkzen** [OneSignal/OneSignal-Xamarin-SDK#96]
It looks like the 3.1.1 nuget version doesn't contain GDPR related code.
When are you planning to create a new nuget version that contains it?

**Comment by Nightsd01** [comment]
Hi @zonkzen , we plan on releasing the new update today with GDPR features. 3.1.1 was released before these features were added.

**Comment by zonkzen** [comment]
It's been 4 days now. Any ETA?
