### ISSUE TITLE
Can't pass launchOptions in during init

### ISSUE THREAD

**Issue by dirkoswanepoel** [OneSignal/OneSignal-Xamarin-SDK#98]
The following method is not available for iOS. Without it, the launchOptions can't be passed in during init.

initWithLaunchOptions:(NSDictionary *)launchOptions appId:(NSString *)appId handleNotificationReceived:(OSHandleNotificationReceivedBlock)receivedCallback handleNotificationAction:(OSHandleNotificationActionBlock)actionCallback settings:(NSDictionary *)settings;

**Comment by rgomezp** [comment]
Closing. Issue still internally under consideration
