### ISSUE TITLE
SetRequiresUserPrivacyConsent method missing

### ISSUE THREAD

**Issue by Adrian-Ionita** [OneSignal/OneSignal-Xamarin-SDK#99]
The latest version does not contain the SetRequiresUserPrivacyConsent method.

![vs](https://user-images.githubusercontent.com/25243645/40404975-40511ff8-5e63-11e8-9ad8-5187ced2f461.png)

**Comment by zonkzen** [comment]
@Adrian-Ionita we're all waiting: https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/96

**Comment by Nightsd01** [comment]
Apologies for the delay. There was a Xamarin coaching issue that caused the ‘IOneSignal‘ interface to not include new functions (it was also missing Email methods we added a while ago). 

We resolved this yesterday in the new release (3.2.0).
